// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `authentication` resource.

/// Some endpoints are public, but some require authentication. We provide all the required endpoints to create an account and authorize yourself.
#[derive(Clone)]
pub struct AuthenticationResource {
    client: crate::client::Galaxy,
}

impl AuthenticationResource {
    pub(crate) fn new(client: crate::client::Galaxy) -> Self {
        Self { client }
    }

    /// Create a user
    pub fn create_user(&self) -> CreateUserRequestBuilder {
        CreateUserRequestBuilder::new(self.client.clone())
    }

    /// Get a token
    pub fn create_token(&self) -> CreateTokenRequestBuilder {
        CreateTokenRequestBuilder::new(self.client.clone())
    }

    /// Get authenticated user
    pub fn list_me(&self) -> ListMeRequestBuilder {
        ListMeRequestBuilder::new(self.client.clone())
    }
}

/// Time to create a user account, eh?
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateUserRequestBuilder {
    client: crate::client::Galaxy,
    body: Option<crate::models::AuthenticationCreateUserBody>,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateUserRequestBuilder {
    fn new(client: crate::client::Galaxy) -> Self {
        Self {
            client,
            body: None,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// User to create
    pub fn body(mut self, value: crate::models::AuthenticationCreateUserBody) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::User, crate::error::Error> {
        let path = "/user/signup".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::User, _>(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Yeah, this is the boring security stuff. Just get your super secret token and move on.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateTokenRequestBuilder {
    client: crate::client::Galaxy,
    body: Option<crate::models::Credentials>,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateTokenRequestBuilder {
    fn new(client: crate::client::Galaxy) -> Self {
        Self {
            client,
            body: None,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Body for credentials to authenticate a user
    pub fn body(mut self, value: crate::models::Credentials) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::Token, crate::error::Error> {
        let path = "/auth/token".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::Token, _>(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Find yourself they say. That's what you can do here.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListMeRequestBuilder {
    client: crate::client::Galaxy,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListMeRequestBuilder {
    fn new(client: crate::client::Galaxy) -> Self {
        Self {
            client,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::User, crate::error::Error> {
        let path = "/me".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::User, _>(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
