// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Resource sub-clients and root accessors.

pub mod authentication;
pub mod celestial_bodies;
pub mod planets;

impl crate::client::Galaxy {
    /// Everything about planets
    pub fn planets(&self) -> crate::resources::planets::PlanetsResource {
        crate::resources::planets::PlanetsResource::new(self.clone())
    }

    /// Celestial bodies are the planets and satellites in the Scalar Galaxy.
    pub fn celestial_bodies(&self) -> crate::resources::celestial_bodies::CelestialBodiesResource {
        crate::resources::celestial_bodies::CelestialBodiesResource::new(self.clone())
    }

    /// Some endpoints are public, but some require authentication. We provide all the required endpoints to create an account and authorize yourself.
    pub fn authentication(&self) -> crate::resources::authentication::AuthenticationResource {
        crate::resources::authentication::AuthenticationResource::new(self.clone())
    }
}
