// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `planets` resource.

#[derive(Clone)]
pub struct Planets {
    client: crate::client::Galaxy,
}

impl Planets {
    pub(crate) fn new(client: crate::client::Galaxy) -> Self {
        Self { client }
    }

    /// Get all planets
    pub fn list_all_data(&self) -> ListAllDataRequest {
        ListAllDataRequest::new(self.client.clone())
    }

    /// Create a planet
    pub fn create(&self) -> CreateRequest {
        CreateRequest::new(self.client.clone())
    }

    /// Get a planet
    pub fn retrieve(&self, planet_id: i64) -> RetrieveRequest {
        RetrieveRequest::new(self.client.clone(), planet_id)
    }

    /// Update a planet
    pub fn update(&self, planet_id: i64) -> UpdateRequest {
        UpdateRequest::new(self.client.clone(), planet_id)
    }

    /// Delete a planet
    pub fn delete(&self, planet_id: i64) -> DeleteRequest {
        DeleteRequest::new(self.client.clone(), planet_id)
    }

    /// Upload an image to a planet
    #[cfg(feature = "multipart")]
    pub fn upload_image(&self, planet_id: i64) -> UploadImageRequest {
        UploadImageRequest::new(self.client.clone(), planet_id)
    }
}

/// It's easy to say you know them all, but do you really? Retrieve all the planets and check whether you missed one.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListAllDataRequest {
    client: crate::client::Galaxy,
    limit: Option<i64>,
    offset: Option<i64>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListAllDataRequest {
    fn new(client: crate::client::Galaxy) -> Self {
        Self {
            client,
            limit: None,
            offset: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// The number of items to return
    pub fn limit(mut self, value: i64) -> Self {
        self.limit = Some(value);
        self
    }

    /// The number of items to skip before starting to collect the result set
    pub fn offset(mut self, value: i64) -> Self {
        self.offset = Some(value);
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::PaginatedResource, crate::error::Error> {
        let path = "/planets".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(value) = &self.limit {
            query.push(("limit".to_string(), crate::http::scalar_value(value)));
        }
        if let Some(value) = &self.offset {
            query.push(("offset".to_string(), crate::http::scalar_value(value)));
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::PaginatedResource, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Time to play god and create a new planet. What do you think? Ah, don't think too much. What could go wrong anyway?
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRequest {
    client: crate::client::Galaxy,
    body: Option<crate::models::Planet>,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateRequest {
    fn new(client: crate::client::Galaxy) -> Self {
        Self {
            client,
            body: None,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Planet
    pub fn body(mut self, value: crate::models::Planet) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::Planet, crate::error::Error> {
        let path = "/planets".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::Planet, _>(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// You'll better learn a little bit more about the planets. It might come in handy once space travel is available for everyone.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveRequest {
    client: crate::client::Galaxy,
    planet_id: i64,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl RetrieveRequest {
    fn new(client: crate::client::Galaxy, planet_id: i64) -> Self {
        Self {
            client,
            planet_id,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::Planet, crate::error::Error> {
        let path = format!(
            "/planets/{}",
            crate::http::encode_path_param(&crate::http::scalar_value(&self.planet_id))
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::Planet, _>(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Sometimes you make mistakes, that's fine. No worries, you can update all planets.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateRequest {
    client: crate::client::Galaxy,
    planet_id: i64,
    body: Option<crate::models::Planet>,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdateRequest {
    fn new(client: crate::client::Galaxy, planet_id: i64) -> Self {
        Self {
            client,
            planet_id,
            body: None,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// New information about the planet
    pub fn body(mut self, value: crate::models::Planet) -> Self {
        self.body = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::Planet, crate::error::Error> {
        let path = format!(
            "/planets/{}",
            crate::http::encode_path_param(&crate::http::scalar_value(&self.planet_id))
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = self.body.as_ref();
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::Planet, _>(http::Method::PUT, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// This endpoint was used to delete planets. Unfortunately, that caused a lot of trouble for planets with life. So, this endpoint is now deprecated and should not be used anymore.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRequest {
    client: crate::client::Galaxy,
    planet_id: i64,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteRequest {
    fn new(client: crate::client::Galaxy, planet_id: i64) -> Self {
        Self {
            client,
            planet_id,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    pub async fn send(self) -> Result<(), crate::error::Error> {
        let path = format!(
            "/planets/{}",
            crate::http::encode_path_param(&crate::http::scalar_value(&self.planet_id))
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        headers.push(("Accept".to_string(), "*/*".to_string()));
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send_empty(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Got a crazy good photo of a planet? Share it with the world!
#[cfg(feature = "multipart")]
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UploadImageRequest {
    client: crate::client::Galaxy,
    planet_id: i64,
    image: Option<crate::transport::multipart::Upload>,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

#[cfg(feature = "multipart")]
impl UploadImageRequest {
    fn new(client: crate::client::Galaxy, planet_id: i64) -> Self {
        Self {
            client,
            planet_id,
            image: None,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// The image file to upload
    pub fn image(mut self, value: crate::transport::multipart::Upload) -> Self {
        self.image = Some(value);
        self
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::PlanetsUploadImageResponse, crate::error::Error> {
        let path = format!(
            "/planets/{}/image",
            crate::http::encode_path_param(&crate::http::scalar_value(&self.planet_id))
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let mut parts: Vec<crate::transport::multipart::Part> = Vec::new();
        if let Some(upload) = self.image {
            parts.push(upload.into_part("image", None));
        }
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send_multipart_parts::<crate::models::PlanetsUploadImageResponse>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                parts,
                true,
                overrides,
            )
            .await
    }
}
