// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Env-less mock round-trips: `MockTransport` + `InstantSleep` drive the real
//! client builder through the auth, retry, deadline, decode, and size-cap
//! paths without a network. Requires the `mock` and `tokio` cargo features
//! (declared via `required-features` in Cargo.toml).
#![allow(unused)]

use std::time::Duration;

use scalar_galaxy::transport::{BoxFuture, InstantSleep, MockTransport, SdkBody, Transport, TransportError};
use scalar_galaxy::*;

/// A response body the generated decode layer accepts for the operation
/// under test.
const RESPONSE_BODY: &str = "{}";

/// A client-credentials token payload the vendored provider accepts. The
/// hour-long lifetime keeps the cached token fresh across a whole test.
const TOKEN_RESPONSE: &str = r#"{"access_token":"mock-access-token","expires_in":3600}"#;

/// A transport whose requests never complete, proving the runtime enforces
/// deadlines even when a backend hangs. (A drained `MockTransport` panics by
/// design, so the deadline test needs its own hang-forever transport.)
#[derive(Debug)]
struct PendingTransport;

impl Transport for PendingTransport {
    fn execute(
        &self,
        _request: ::http::Request<SdkBody>,
    ) -> BoxFuture<'_, Result<::http::Response<SdkBody>, TransportError>> {
        Box::pin(std::future::pending())
    }
}

/// Configured credentials land on the recorded request exactly as the
/// generated `Auth::apply` renders them.
#[tokio::test]
async fn authenticates_requests_with_configured_credentials() {
    let mock = MockTransport::new();
    mock.enqueue(200, RESPONSE_BODY);
    let client = Galaxy::builder()
        .base_url("http://mock.invalid")
        .transport(mock.clone())
        .sleeper(InstantSleep)
        .max_retries(0)
        .username("test-username")
        .password("test-password")
        .build()
        .expect("client builds");
    let result: Result<(), Error> = async {
        let _ = client.planets().list_all_data().send().await?;
        Ok(())
    }
    .await;
    assert!(result.is_ok(), "authenticated call failed: {result:?}");
    let recorded = mock.requests();
    assert_eq!(recorded.len(), 1);
    let authorization = recorded[0].headers.get(::http::header::AUTHORIZATION).expect("authorization header");
    assert_eq!(authorization.to_str().expect("ascii header"), "Basic dGVzdC11c2VybmFtZTp0ZXN0LXBhc3N3b3Jk");
}

/// The ordinary client-credentials request: one exchange, then the fetched
/// bearer on every call — the cached token is not re-fetched per request.
#[tokio::test]
async fn oauth_fetches_one_token_and_reuses_it() {
    let mock = MockTransport::new();
    mock.enqueue(200, TOKEN_RESPONSE);
    mock.enqueue(200, "{}");
    mock.enqueue(200, "{}");
    let client = Galaxy::builder()
        .base_url("http://mock.invalid")
        .transport(mock.clone())
        .sleeper(InstantSleep)
        .max_retries(0)
        .client_id("test-client-id")
        .client_secret("test-client-secret")
        .build()
        .expect("client builds");
    let result: Result<(), Error> = async {
        let _ = client.planets().list_all_data().send().await?;
        Ok(())
    }
    .await;
    assert!(result.is_ok(), "first authenticated call failed: {result:?}");
    let result: Result<(), Error> = async {
        let _ = client.planets().list_all_data().send().await?;
        Ok(())
    }
    .await;
    assert!(result.is_ok(), "second authenticated call failed: {result:?}");
    let recorded = mock.requests();
    assert_eq!(recorded.len(), 3, "expected one token request and two API requests");
    assert_eq!(recorded.iter().filter(|request| request.uri.to_string().contains("/oauth/token")).count(), 1, "the token endpoint must be dialed exactly once, not per request");
    for request in &recorded[1..] {
        let authorization = request.headers.get(::http::header::AUTHORIZATION).expect("authorization header");
        assert_eq!(authorization.to_str().expect("ascii header"), "Bearer mock-access-token");
    }
}

/// The exchange asks for exactly the scopes the caller configured.
///
/// The default is every scope the API description documents; a client
/// granted only a subset must be able to narrow it, since an authorization
/// server refuses an over-broad request (`invalid_scope`) rather than
/// downgrading it — which would otherwise fail the first API call.
#[tokio::test]
async fn oauth_requests_only_the_configured_scopes() {
    let mock = MockTransport::new();
    mock.enqueue(200, TOKEN_RESPONSE);
    mock.enqueue(200, "{}");
    let client = Galaxy::builder()
        .base_url("http://mock.invalid")
        .transport(mock.clone())
        .sleeper(InstantSleep)
        .max_retries(0)
        .client_id("test-client-id")
        .client_secret("test-client-secret")
        .oauth_scopes(["read:account"])
        .build()
        .expect("client builds");
    let result: Result<(), Error> = async {
        let _ = client.planets().list_all_data().send().await?;
        Ok(())
    }
    .await;
    assert!(result.is_ok(), "authenticated call failed: {result:?}");
    let recorded = mock.requests();
    let token_form = String::from_utf8_lossy(&recorded[0].body);
    assert!(
        token_form.contains("scope=read%3Aaccount"),
        "the configured scope did not reach the token request"
    );
    assert!(
        !token_form.contains("write%3Aplanets"),
        "the exchange asked for a scope the caller did not configure"
    );
}

/// A request answered by another configured alternative never dials the
/// token endpoint: the credential decision happens before (and decides)
/// the exchange, so a client holding client-credentials pays nothing for
/// them on requests that do not use them.
#[tokio::test]
async fn oauth_token_endpoint_is_untouched_when_another_credential_wins() {
    let mock = MockTransport::new();
    mock.enqueue(200, "{}");
    let client = Galaxy::builder()
        .base_url("http://mock.invalid")
        .transport(mock.clone())
        .sleeper(InstantSleep)
        .max_retries(0)
        .client_id("test-client-id")
        .client_secret("test-client-secret")
        .username("test-username")
        .password("test-password")
        .build()
        .expect("client builds");
    let result: Result<(), Error> = async {
        let _ = client.planets().list_all_data().send().await?;
        Ok(())
    }
    .await;
    assert!(result.is_ok(), "authenticated call failed: {result:?}");
    let recorded = mock.requests();
    assert_eq!(recorded.len(), 1, "only the API request should have been sent");
    assert_eq!(recorded.iter().filter(|request| request.uri.to_string().contains("/oauth/token")).count(), 0, "the token endpoint must not be dialed for this request");
    let authorization = recorded[0].headers.get(::http::header::AUTHORIZATION).expect("authorization header");
    assert_eq!(authorization.to_str().expect("ascii header"), "Basic dGVzdC11c2VybmFtZTp0ZXN0LXBhc3N3b3Jk");
}

/// A 429 followed by a 200: the runtime replays this crate's anchor
/// operation once and succeeds within `max_retries(1)`, sending exactly two
/// requests. (This drives one operation; that the 429 replay is independent
/// of HTTP method is covered by the runtime's own retry-taxonomy tests in
/// `src/http.rs`.)
#[tokio::test]
async fn retries_transient_429_and_succeeds() {
    let mock = MockTransport::new();
    mock.enqueue(429, "{}");
    mock.enqueue(200, RESPONSE_BODY);
    let client = Galaxy::builder()
        .base_url("http://mock.invalid")
        .transport(mock.clone())
        .sleeper(InstantSleep)
        .max_retries(1)
        .build()
        .expect("client builds");
    let result: Result<(), Error> = async {
        let _ = client.planets().list_all_data().send().await?;
        Ok(())
    }
    .await;
    assert!(result.is_ok(), "retried call failed: {result:?}");
    assert_eq!(mock.requests().len(), 2, "expected the 429 to be retried exactly once");
}

/// A hanging transport trips the builder deadline: the runtime races the
/// sleeper against `Transport::execute`, so no backend can drop timeouts.
#[tokio::test]
async fn deadline_yields_timeout_transport_error() {
    let client = Galaxy::builder()
        .base_url("http://mock.invalid")
        .transport(PendingTransport)
        .max_retries(0)
        .timeout(Duration::from_millis(50))
        .build()
        .expect("client builds");
    let result: Result<(), Error> = async {
        let _ = client.planets().list_all_data().send().await?;
        Ok(())
    }
    .await;
    match result {
        Err(Error::Transport(error)) => {
            assert!(error.is_timeout(), "expected a timeout, got {error:?}");
        }
        other => panic!("expected Error::Transport(timeout), got {other:?}"),
    }
}

/// A queued success body decodes through the typed `send()` path.
#[tokio::test]
async fn decodes_typed_response_from_queued_body() {
    let mock = MockTransport::new();
    mock.enqueue(200, RESPONSE_BODY);
    let client = Galaxy::builder()
        .base_url("http://mock.invalid")
        .transport(mock.clone())
        .sleeper(InstantSleep)
        .max_retries(0)
        .build()
        .expect("client builds");
    let result: Result<(), Error> = async {
        let _ = client.planets().list_all_data().send().await?;
        Ok(())
    }
    .await;
    assert!(result.is_ok(), "decode failed: {result:?}");
    assert_eq!(mock.requests().len(), 1);
}

/// A body larger than `max_response_size` is rejected before buffering,
/// bounding memory against attacker-influencable responses.
#[tokio::test]
async fn oversized_response_is_rejected() {
    let mock = MockTransport::new();
    mock.enqueue(200, RESPONSE_BODY);
    let client = Galaxy::builder()
        .base_url("http://mock.invalid")
        .transport(mock.clone())
        .sleeper(InstantSleep)
        .max_retries(0)
        .max_response_size(RESPONSE_BODY.len() - 1)
        .build()
        .expect("client builds");
    let result: Result<(), Error> = async {
        let _ = client.planets().list_all_data().send().await?;
        Ok(())
    }
    .await;
    match result {
        Err(Error::ResponseTooLarge { limit }) => assert_eq!(limit, RESPONSE_BODY.len() - 1),
        other => panic!("expected Error::ResponseTooLarge, got {other:?}"),
    }
}

/// A wholesale `default_headers` replacement clears a previously recorded
/// invalid `default_header` entry — the record described a map that no
/// longer exists — so `build()` succeeds on the documented replace path.
#[test]
fn default_headers_replacement_clears_invalid_entry() {
    let client = Galaxy::builder()
        .base_url("http://mock.invalid")
        .transport(MockTransport::new())
        .default_header("bad header name", "value")
        .default_headers(::http::HeaderMap::new())
        .build();
    assert!(client.is_ok(), "replacement should clear the invalid-header record: {:?}", client.err());
}
