// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `authentication`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

/// A user
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Credentials to authenticate a user
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Credentials {
    pub email: String,
    pub password: String,
}

/// A token to authenticate a user
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Token {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationCreateUserBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub email: String,
    pub password: String,
}

impl AuthenticationCreateUserBody {
    /// Creates a new `AuthenticationCreateUserBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `AuthenticationCreateUserBody { id: Some(…), ..AuthenticationCreateUserBody::new(email, password) }`.
    pub fn new(email: impl Into<String>, password: impl Into<String>) -> Self {
        Self {
            id: None,
            name: None,
            email: email.into(),
            password: password.into(),
        }
    }
}
