// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `celestial_bodies`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

/// A celestial body which can be either a planet or a satellite
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
#[non_exhaustive]
pub enum CelestialBody {
    #[serde(rename = "terrestrial")]
    Planet(Planet),
    #[serde(rename = "gas_giant")]
    Planet_(Planet),
    #[serde(rename = "ice_giant")]
    Planet__(Planet),
    #[serde(rename = "dwarf")]
    Planet___(Planet),
    #[serde(rename = "super_earth")]
    Planet____(Planet),
    #[serde(rename = "moon")]
    Satellite(Satellite),
    #[serde(rename = "asteroid")]
    Satellite_(Satellite),
    #[serde(rename = "comet")]
    Satellite__(Satellite),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

/// Every satellite in the Scalar Galaxy
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Satellite {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Diameter in kilometers
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub diameter: Option<f64>,
    #[serde(default, skip_serializing)]
    pub r#type: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub orbit: Option<serde_json::Value>,
}

impl Satellite {
    /// Creates a new `Satellite` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `Satellite { id: Some(…), ..Satellite::new(name) }`.
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            id: None,
            name: name.into(),
            description: None,
            diameter: None,
            r#type: String::new(),
            orbit: None,
        }
    }
}
