// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `planets`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

/// A planet in the Scalar Galaxy
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Planet {
    pub id: i64,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing)]
    pub r#type: String,
    /// A score from 0 to 1 indicating potential habitability
    #[serde(rename = "habitabilityIndex", default, skip_serializing_if = "Option::is_none")]
    pub habitability_index: Option<f64>,
    #[serde(rename = "physicalProperties", default, skip_serializing_if = "Option::is_none")]
    pub physical_properties: Option<PlanetPhysicalProperties>,
    /// Atmospheric composition
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub atmosphere: Option<Vec<PlanetAtmosphere>>,
    #[serde(rename = "discoveredAt", default, skip_serializing_if = "Option::is_none")]
    pub discovered_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub satellites: Option<Vec<Satellite>>,
    /// A user
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creator: Option<User>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "lastUpdated", default, skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// URL which gets invoked upon a successful operation
    #[serde(rename = "successCallbackUrl", default, skip_serializing_if = "Option::is_none")]
    pub success_callback_url: Option<String>,
    /// URL which gets invoked upon a failed operation
    #[serde(rename = "failureCallbackUrl", default, skip_serializing_if = "Option::is_none")]
    pub failure_callback_url: Option<String>,
}

impl Planet {
    /// Creates a new `Planet` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `Planet { description: Some(…), ..Planet::new(id, name) }`.
    pub fn new(id: i64, name: impl Into<String>) -> Self {
        Self {
            id,
            name: name.into(),
            description: None,
            r#type: String::new(),
            habitability_index: None,
            physical_properties: None,
            atmosphere: None,
            discovered_at: None,
            image: None,
            satellites: None,
            creator: None,
            tags: None,
            last_updated: None,
            success_callback_url: None,
            failure_callback_url: None,
        }
    }
}

/// A generic paginated resource. Specializing schemas bind the item type by declaring a `$dynamicAnchor` named `itemType`, the JSON Schema 2020-12 way to express `PaginatedResource<T>`.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct PaginatedResource {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<PaginatedResourceMeta>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct PlanetsDelteImageResponse {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The URL where the uploaded image can be accessed
    #[serde(rename = "imageUrl", default, skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// Timestamp when the image was uploaded
    #[serde(rename = "uploadedAt", default, skip_serializing_if = "Option::is_none")]
    pub uploaded_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Size of the uploaded image in bytes
    #[serde(rename = "fileSize", default, skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i64>,
    /// The content type of the uploaded image
    #[serde(rename = "mimeType", default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PlanetsDelteImageBody {
    /// The image file to upload
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PlanetPhysicalProperties {
    /// Mass in Earth masses (must be greater than 0)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mass: Option<f64>,
    /// Radius in Earth radii (must be greater than 0)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub radius: Option<f64>,
    /// Surface gravity in Earth g
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gravity: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub temperature: Option<PlanetPhysicalPropertiesTemperature>,
    /// Additional properties not captured by the named fields.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PlanetPhysicalPropertiesTemperature {
    /// Minimum temperature in Kelvin
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    /// Maximum temperature in Kelvin
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
    /// Average temperature in Kelvin
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub average: Option<f64>,
    /// Additional properties not captured by the named fields.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, f64>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PlanetAtmosphere {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compound: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub percentage: Option<f64>,
    /// Additional properties not captured by the named fields.
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, String>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct PaginatedResourceMeta {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub offset: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}
