// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The Galaxy API client.

use std::sync::Arc;
use std::time::Duration;

use http::Method;
use serde::Serialize;
use serde::de::DeserializeOwned;

use crate::error::Error;
use crate::transport::{SdkBody, Sleep, Transport};

const DEFAULT_MAX_RETRIES: u32 = 2;
// Default per-attempt deadline, applied in dispatch only to requests with
// buffered non-multipart bodies: the deadline race spans the whole attempt
// including the request-body upload, so a default the caller never chose
// must not kill a streaming upload of unknown size — nor a multipart form,
// which buffers file parts of unbounded size (see `ClientBuilder::timeout`).
const DEFAULT_TIMEOUT: Duration = Duration::from_secs(60);
const USER_AGENT: &str = concat!("scalar-galaxy/", env!("CARGO_PKG_VERSION"));
const IDEMPOTENCY_HEADER: &str = "Idempotency-Key";

/// A named API environment with a preset base URL.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[non_exhaustive]
pub enum Environment {
    /// The `production` environment.
    #[default]
    Production,
    /// The `responds_with_your_request_data` environment.
    RespondsWithYourRequestData,
}

impl Environment {
    /// The base URL for this environment.
    pub fn base_url(self) -> &'static str {
        match self {
            Self::Production => "https://galaxy.scalar.com",
            Self::RespondsWithYourRequestData => "{protocol}://void.scalar.com/{path}",
        }
    }
}

/// Credentials applied to every outgoing request.
#[derive(Clone, Default)]
struct Auth {
    bearer_token: Option<String>,
    username: Option<String>,
    password: Option<String>,
    api_key_header: Option<String>,
    api_key_query: Option<String>,
    api_key_cookie: Option<String>,
    access_token: Option<String>,
}

impl Auth {
    /// Applies the configured credentials to a request's headers and URL.
    ///
    /// One renderer serves both HTTP dispatch and the WebSocket handshake,
    /// so the two security-sensitive paths can never drift apart. Header
    /// credentials are validated through `auth_value`, which marks them
    /// sensitive and never echoes them in errors; query credentials ride
    /// the URL's form-urlencoded serializer.
    ///
    /// `oauth_token` carries the access token the client-credentials
    /// provider fetched for this request (dispatch resolves it, since this
    /// renderer is sync); a caller-supplied static token still wins, and a
    /// `None` here means no token was needed — or the exchange failed and
    /// another configured alternative is taking over.
    fn apply(&self, headers: &mut http::HeaderMap, url: &mut url::Url, oauth_token: Option<&str>) -> Result<(), Error> {
        if self.username.is_some() && self.password.is_some() {
            if let Some(user) = &self.username {
                let pass = self.password.as_deref().unwrap_or("");
                let token = base64_encode(format!("{user}:{pass}").as_bytes());
                headers.insert(http::header::AUTHORIZATION, auth_value(&format!("Basic {token}"))?);
            }
        } else if self.api_key_header.is_some() && self.api_key_query.is_some() {
            if let Some(value) = &self.api_key_header {
                headers.insert(header_name("X-API-Key")?, auth_value(value)?);
            }
            if let Some(value) = &self.api_key_query {
                url.query_pairs_mut().append_pair("api_key", value);
            }
        } else if self.bearer_token.is_some() {
            if let Some(value) = &self.bearer_token {
                headers.insert(http::header::AUTHORIZATION, auth_value(&format!("Bearer {value}"))?);
            }
        } else if self.api_key_query.is_some() {
            if let Some(value) = &self.api_key_query {
                url.query_pairs_mut().append_pair("api_key", value);
            }
        } else if self.api_key_header.is_some() {
            if let Some(value) = &self.api_key_header {
                headers.insert(header_name("X-API-Key")?, auth_value(value)?);
            }
        } else if self.api_key_cookie.is_some() {
            if let Some(value) = &self.api_key_cookie {
                headers.insert(http::header::COOKIE, auth_value(&format!("{}={}", "api_key", value))?);
            }
        } else if self.access_token.is_some() || oauth_token.is_some() {
            if let Some(value) = self.access_token.as_deref().or(oauth_token) {
                headers.insert(http::header::AUTHORIZATION, auth_value(&format!("Bearer {value}"))?);
            }
        }
        Ok(())
    }

    /// Index of the first alternative whose credentials are all configured
    /// — the one [`apply`](Self::apply) renders for this request.
    ///
    /// `oauth_ready` stands in for a token the client-credentials provider
    /// could still fetch, so the OAuth-backed alternative stays selectable
    /// before any exchange happens and this answer matches what `apply`
    /// selects once the token is in hand. Passing `false` instead asks
    /// which alternative could authenticate the request with no token at
    /// all.
    fn selected_group(&self, oauth_ready: bool) -> Option<usize> {
        if self.username.is_some() && self.password.is_some() {
            Some(0)
        } else if self.api_key_header.is_some() && self.api_key_query.is_some() {
            Some(1)
        } else if self.bearer_token.is_some() {
            Some(2)
        } else if self.api_key_query.is_some() {
            Some(3)
        } else if self.api_key_header.is_some() {
            Some(4)
        } else if self.api_key_cookie.is_some() {
            Some(5)
        } else if self.access_token.is_some() || oauth_ready {
            Some(6)
        } else {
            None
        }
    }

    /// Whether this request needs an access token from the client-credentials
    /// provider.
    ///
    /// Dispatch calls this *before* awaiting anything: a caller-supplied static
    /// token wins over the exchange, and a request whose winning credential
    /// group carries its own credentials never dials the token endpoint. Only
    /// a `true` here reaches the provider.
    fn wants_oauth_token(&self, oauth_ready: bool) -> bool {
        if self.access_token.is_some() {
            return false;
        }
        matches!(self.selected_group(oauth_ready), Some(6))
    }

    /// Whether another configured alternative can authenticate this request
    /// with no client-credentials token.
    ///
    /// Consulted only when an exchange fails: a credential set the client
    /// cannot obtain is unavailable, not fatal, so the chain falls through
    /// to the next satisfied alternative instead of failing a request
    /// another credential already covers. An arm that applies everything it
    /// holds has no alternatives, so a failed exchange there stays fatal.
    fn authenticates_without_oauth_token(&self) -> bool {
        self.selected_group(false).is_some()
    }
}

/// Shared client state held behind an `Arc` so cloning a client is cheap.
struct Inner {
    /// The pluggable HTTP backend every request goes through.
    transport: Arc<dyn Transport>,
    /// Async timer used for retry backoff and deadline enforcement.
    sleep: Arc<dyn Sleep>,
    base_url: url::Url,
    auth: Auth,
    /// Maximum retry attempts for transient failures.
    max_retries: u32,
    /// The caller-configured deadline; `None` means only the buffered
    /// non-multipart `DEFAULT_TIMEOUT` applies, resolved per request in
    /// `dispatch`.
    deadline: Option<Duration>,
    /// Cap on buffered response bodies, enforced by the decode layer.
    max_response_size: usize,
    /// Headers applied to every request, before per-request headers and auth.
    default_headers: http::HeaderMap,
    /// Pre-validated `User-Agent` value sent as a plain header on every
    /// request, so it applies identically to every transport (including BYO).
    user_agent: http::HeaderValue,
    /// OAuth client-credentials token provider, present only when both
    /// the client id and secret were configured. It caches and refreshes
    /// tokens over this client's own transport and timer.
    oauth: Option<crate::oauth::TokenProvider>,
}

/// Per-request policy overrides set by operation builders (`.timeout()`,
/// `.max_retries()`); unset fields fall back to the client-level defaults.
#[derive(Clone, Copy, Default)]
pub(crate) struct RequestOverrides {
    /// Deadline override for this request only.
    pub(crate) timeout: Option<Duration>,
    /// Retry-count override for this request only.
    pub(crate) max_retries: Option<u32>,
}

/// How a request body is serialized onto the wire.
enum ContentEncoding {
    /// `application/json` body.
    Json,
    /// `multipart/form-data` body, already lowered to typed parts.
    #[cfg(feature = "multipart")]
    Multipart(Vec<crate::transport::multipart::Part>),
}

/// Asynchronous client for the Galaxy API.
///
/// Cloning is cheap: all state is shared behind an `Arc`. Construct one with
/// [`Galaxy::builder`] or [`Galaxy::from_env`].
#[derive(Clone)]
pub struct Galaxy {
    inner: Arc<Inner>,
}

impl Galaxy {
    /// Starts building a client with the fluent builder.
    pub fn builder() -> GalaxyBuilder {
        GalaxyBuilder::new()
    }

    /// Builds a client, reading credentials from the environment.
    ///
    /// Each credential is read from its conventional environment variable;
    /// missing variables are simply left unset.
    pub fn from_env() -> Result<Self, Error> {
        let mut builder = Self::builder();
        if let Some(value) = read_env("SCALAR_BASE_URL") {
            builder = builder.base_url(value);
        }
        if let Some(value) = read_env("SCALAR_BEARER_TOKEN") {
            builder = builder.bearer_token(value);
        }
        if let Some(value) = read_env("SCALAR_USERNAME") {
            builder = builder.username(value);
        }
        if let Some(value) = read_env("SCALAR_PASSWORD") {
            builder = builder.password(value);
        }
        if let Some(value) = read_env("SCALAR_API_KEY_HEADER") {
            builder = builder.api_key_header(value);
        }
        if let Some(value) = read_env("SCALAR_API_KEY_QUERY") {
            builder = builder.api_key_query(value);
        }
        if let Some(value) = read_env("SCALAR_API_KEY_COOKIE") {
            builder = builder.api_key_cookie(value);
        }
        if let Some(value) = read_env("SCALAR_ACCESS_TOKEN") {
            builder = builder.access_token(value);
        }
        if let Some(value) = read_env("SCALAR_CLIENT_ID") {
            builder = builder.client_id(value);
        }
        if let Some(value) = read_env("SCALAR_CLIENT_SECRET") {
            builder = builder.client_secret(value);
        }
        if let Some(value) = read_env("SCALAR_OAUTH_SCOPES") {
            builder = builder.oauth_scopes(value.split_whitespace());
        }
        builder.build()
    }
}

impl std::fmt::Debug for Galaxy {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Galaxy")
            .field("base_url", &self.inner.base_url.as_str())
            .field("max_retries", &self.inner.max_retries)
            .field("timeout", &self.inner.deadline)
            .finish_non_exhaustive()
    }
}

#[allow(dead_code, clippy::too_many_arguments)]
impl Galaxy {
    /// Resolves the OAuth access token to apply to a request, if any.
    ///
    /// Returns `None` when the caller supplied a static token (it wins, and no
    /// exchange happens) or when no client id/secret was configured. Otherwise
    /// the provider's cache answers, fetching or refreshing over this client's
    /// transport only when the cached token is missing or close to expiring.
    async fn oauth_access_token(&self) -> Result<Option<String>, Error> {
        if self.inner.auth.access_token.is_some() {
            return Ok(None);
        }
        match &self.inner.oauth {
            Some(provider) => provider
                .access_token(
                    &*self.inner.transport,
                    &*self.inner.sleep,
                    self.inner.max_retries,
                    self.inner.deadline,
                    self.inner.max_response_size,
                )
                .await
                .map(Some),
            None => Ok(None),
        }
    }

    /// Builds, authenticates, and sends a request, decoding a JSON response.
    pub(crate) async fn send<T: DeserializeOwned, B: Serialize>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        body: Option<&B>,
        apply_auth: bool,
        overrides: RequestOverrides,
    ) -> Result<T, Error> {
        let response = self.dispatch(method, path, query, headers, body, apply_auth, overrides, ContentEncoding::Json).await?;
        crate::http::decode_json(response, self.inner.max_response_size).await
    }

    /// Like [`send`](Self::send) but for operations that return no content.
    pub(crate) async fn send_empty<B: Serialize>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        body: Option<&B>,
        apply_auth: bool,
        overrides: RequestOverrides,
    ) -> Result<(), Error> {
        let response = self.dispatch(method, path, query, headers, body, apply_auth, overrides, ContentEncoding::Json).await?;
        crate::http::decode_empty(response, self.inner.max_response_size).await
    }

    /// Encodes `parts` as `multipart/form-data` and returns the raw response.
    ///
    /// The vendored encoder generates the boundary and decides retryability: an
    /// all-buffered form stays replayable, while any streamed part makes the
    /// request single-attempt.
    #[cfg(feature = "multipart")]
    pub(crate) async fn send_multipart_raw(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        parts: Vec<crate::transport::multipart::Part>,
        apply_auth: bool,
        overrides: RequestOverrides,
    ) -> Result<http::Response<SdkBody>, Error> {
        self.dispatch(
            method,
            path,
            query,
            headers,
            None::<&serde_json::Value>,
            apply_auth,
            overrides,
            ContentEncoding::Multipart(parts),
        )
        .await
    }

    /// Like [`send`](Self::send) but sends a `multipart/form-data` form.
    #[cfg(feature = "multipart")]
    pub(crate) async fn send_multipart_parts<T: DeserializeOwned>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        parts: Vec<crate::transport::multipart::Part>,
        apply_auth: bool,
        overrides: RequestOverrides,
    ) -> Result<T, Error> {
        let response = self
            .send_multipart_raw(method, path, query, headers, parts, apply_auth, overrides)
            .await?;
        crate::http::decode_json(response, self.inner.max_response_size).await
    }

    /// Like [`send_multipart_parts`](Self::send_multipart_parts) but for operations that return no content.
    #[cfg(feature = "multipart")]
    pub(crate) async fn send_multipart_empty(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        parts: Vec<crate::transport::multipart::Part>,
        apply_auth: bool,
        overrides: RequestOverrides,
    ) -> Result<(), Error> {
        let response = self
            .send_multipart_raw(method, path, query, headers, parts, apply_auth, overrides)
            .await?;
        crate::http::decode_empty(response, self.inner.max_response_size).await
    }

    /// Like [`send_multipart_parts`](Self::send_multipart_parts) but returns the raw response bytes.
    #[cfg(feature = "multipart")]
    pub(crate) async fn send_multipart_bytes(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        parts: Vec<crate::transport::multipart::Part>,
        apply_auth: bool,
        overrides: RequestOverrides,
    ) -> Result<bytes::Bytes, Error> {
        let response = self
            .send_multipart_raw(method, path, query, headers, parts, apply_auth, overrides)
            .await?;
        crate::http::decode_bytes(response, self.inner.max_response_size).await
    }

    /// Sends a request and returns the raw response, for streaming operations.
    pub(crate) async fn send_raw<B: Serialize>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        body: Option<&B>,
        apply_auth: bool,
        overrides: RequestOverrides,
    ) -> Result<http::Response<SdkBody>, Error> {
        self.dispatch(method, path, query, headers, body, apply_auth, overrides, ContentEncoding::Json).await
    }

    /// Assembles a request (URL, query, headers, body, auth) and sends it with retries.
    async fn dispatch<B: Serialize>(
        &self,
        method: Method,
        path: &str,
        query: &[(String, String)],
        headers: &[(String, String)],
        body: Option<&B>,
        apply_auth: bool,
        overrides: RequestOverrides,
        content: ContentEncoding,
    ) -> Result<http::Response<SdkBody>, Error> {
        let mut url = if path.starts_with("http://") || path.starts_with("https://") {
            url::Url::parse(path).map_err(|error| Error::Config(error.to_string()))?
        } else {
            self.inner
                .base_url
                .join(path.trim_start_matches('/'))
                .map_err(|error| Error::Config(error.to_string()))?
        };
        ensure_same_origin(&self.inner.base_url, &url)?;
        if !query.is_empty() {
            // Query pairs go through the url crate's form_urlencoded serializer,
            // which percent-encodes each name and value.
            let mut pairs = url.query_pairs_mut();
            for (name, value) in query {
                pairs.append_pair(name, value);
            }
        }
        let mut header_map = self.inner.default_headers.clone();
        for (index, (name, value)) in headers.iter().enumerate() {
            let parsed = header_name(name)?;
            // A per-request header overrides a colliding default header (the
            // contract documented on `default_header`): the name's first
            // occurrence clears the inherited values, then `append` keeps every
            // per-request value so repeated params (array headers) all survive.
            if !headers[..index].iter().any(|(seen, _)| seen.eq_ignore_ascii_case(name)) {
                header_map.remove(&parsed);
            }
            header_map.append(parsed, header_value(name, value)?);
        }
        // The SDK user agent rides as a plain header so every transport sends it
        // (including BYO ones). Checked after per-request headers land so a
        // default-header or per-request User-Agent overrides it — the wire never
        // carries two UA lines.
        if !header_map.contains_key(http::header::USER_AGENT) {
            header_map.insert(http::header::USER_AGENT, self.inner.user_agent.clone());
        }
        let keyed = headers.iter().any(|(name, _)| name.eq_ignore_ascii_case(IDEMPOTENCY_HEADER));
        // An explicit timeout applies to every request, but the *default*
        // deadline must not kill a multipart form: its file parts can be
        // arbitrarily large. The encoding tag decides, never content sniffing.
        #[cfg(feature = "multipart")]
        let default_deadline_eligible = !matches!(&content, ContentEncoding::Multipart(_));
        // Without the multipart feature no multipart body can be built, so
        // every buffered body is eligible for the default deadline.
        #[cfg(not(feature = "multipart"))]
        let default_deadline_eligible = true;
        let mut request_body = SdkBody::empty();
        match content {
            #[cfg(feature = "multipart")]
            ContentEncoding::Multipart(parts) => {
                let (content_type, encoded) = crate::transport::multipart::encode(parts);
                header_map.insert(http::header::CONTENT_TYPE, header_value("content-type", &content_type)?);
                request_body = encoded;
            }
            ContentEncoding::Json => {
                if let Some(body) = body {
                    // `entry`+`or_insert` so a spec-declared Content-Type header param
                    // (already appended via `headers`) wins over the JSON default. The
                    // form/multipart arms insert unconditionally: the runtime owns those
                    // encodings (the multipart boundary is generated per request).
                    header_map
                        .entry(http::header::CONTENT_TYPE)
                        .or_insert(http::HeaderValue::from_static("application/json"));
                    request_body = SdkBody::from_bytes(serde_json::to_vec(body)?);
                }
            }
        }
        if apply_auth {
            // Only a request whose winning credential group applies the OAuth
            // bearer pays for a token exchange; one that another configured
            // alternative satisfies never dials the token endpoint at all.
            let mut oauth_token = None;
            if self.inner.auth.wants_oauth_token(self.inner.oauth.is_some()) {
                match self.oauth_access_token().await {
                    Ok(token) => oauth_token = token,
                    // A credential the client cannot obtain is unavailable, not
                    // fatal: when another configured alternative can authenticate
                    // this request, fall through to it — `apply` re-selects with
                    // no token in hand and picks the next satisfied group. With no
                    // such alternative the exchange failure is the request failure.
                    Err(error) => {
                        if !self.inner.auth.authenticates_without_oauth_token() {
                            return Err(error);
                        }
                        crate::http::trace_oauth_fallback();
                    }
                }
            }
            self.inner.auth.apply(&mut header_map, &mut url, oauth_token.as_deref())?;
        }
        let mut request = http::Request::new(request_body);
        *request.method_mut() = method;
        *request.uri_mut() = url
            .as_str()
            .parse::<http::Uri>()
            .map_err(|error| Error::Config(error.to_string()))?;
        *request.headers_mut() = header_map;
        let max_retries = overrides.max_retries.unwrap_or(self.inner.max_retries);
        // An explicit timeout (per-request or builder-wide) applies to every
        // request — the caller asked for it. The default applies only when the
        // body is buffered AND not multipart: the deadline race covers the
        // upload too, and a default must not kill a streaming upload of unknown
        // duration — nor a multipart form, whose buffered file parts can be
        // arbitrarily large (see `default_deadline_eligible` above, computed
        // from the encoding tag rather than by sniffing the body).
        let deadline = overrides
            .timeout
            .or(self.inner.deadline)
            .or_else(|| {
                (default_deadline_eligible && request.body().as_bytes().is_some()).then_some(DEFAULT_TIMEOUT)
            });
        crate::http::send_with_retries(
            &*self.inner.transport,
            &*self.inner.sleep,
            request,
            max_retries,
            deadline,
            keyed,
        )
        .await
    }
}

/// Fluent builder for [`Galaxy`].
#[derive(Default)]
pub struct GalaxyBuilder {
    base_url: Option<String>,
    environment: Option<Environment>,
    transport: Option<Arc<dyn Transport>>,
    sleep: Option<Arc<dyn Sleep>>,
    timeout: Option<Duration>,
    max_retries: Option<u32>,
    max_response_size: Option<usize>,
    default_headers: http::HeaderMap,
    /// First invalid header handed to `default_header`, reported by `build`
    /// so the setters stay infallible without swallowing the mistake.
    invalid_header: Option<String>,
    bearer_token: Option<String>,
    username: Option<String>,
    password: Option<String>,
    api_key_header: Option<String>,
    api_key_query: Option<String>,
    api_key_cookie: Option<String>,
    access_token: Option<String>,
    client_id: Option<String>,
    client_secret: Option<String>,
    /// Space-joined scope override for the token exchange.
    oauth_scopes: Option<String>,
}

impl GalaxyBuilder {
    /// Creates an empty builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Overrides the base URL the client sends requests to.
    /// The default is the base URL of [`Environment::Production`].
    pub fn base_url(mut self, base_url: impl Into<String>) -> Self {
        self.base_url = Some(base_url.into());
        self
    }

    /// Selects a named environment, setting the base URL.
    /// The default is [`Environment::Production`].
    pub fn environment(mut self, environment: Environment) -> Self {
        self.environment = Some(environment);
        self
    }

    /// Supplies a custom HTTP transport.
    ///
    /// The default (with the `reqwest` cargo feature, which is on by
    /// default) is the bundled `ReqwestTransport`. Bring your own backend
    /// by implementing [`crate::transport::Transport`]; with
    /// `default-features = false` a transport must be supplied here or
    /// [`build`](Self::build) returns a configuration error.
    pub fn transport(mut self, transport: impl Transport + 'static) -> Self {
        self.transport = Some(Arc::new(transport));
        self
    }

    /// Supplies a custom async timer for retry backoff and deadlines.
    ///
    /// The default is the tokio-backed sleeper whenever the `tokio` cargo
    /// feature is enabled (the default `reqwest` backend enables it). A
    /// custom transport on a non-tokio runtime must supply one, since
    /// retries and request deadlines need a timer to enforce.
    pub fn sleeper(mut self, sleeper: impl Sleep + 'static) -> Self {
        self.sleep = Some(Arc::new(sleeper));
        self
    }

    /// Sets the request deadline, applied to every request.
    ///
    /// The deadline bounds each attempt **per attempt**, from dispatch
    /// until response headers arrive — request-body upload included —
    /// enforced uniformly by the runtime for every transport. Each retry
    /// gets a fresh deadline, so total wall time can reach roughly
    /// `(1 + max_retries) × timeout` plus backoff between attempts. Once
    /// headers arrive, streamed response bodies (SSE, downloads) are never
    /// deadline-killed.
    ///
    /// Unset, a 60-second default applies, but only to requests with
    /// buffered non-multipart bodies: a streaming upload of unknown size
    /// gets no default deadline, and neither does a multipart form (its
    /// buffered file parts can be arbitrarily large). An explicit timeout
    /// — set here or per request via `.timeout()` on an operation builder
    /// — covers streaming and multipart uploads too.
    pub fn timeout(mut self, timeout: Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Sets the maximum number of retry attempts for transient failures.
    /// The default is 2.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Caps how many bytes of a buffered response body the client reads.
    /// The default is 64 MiB.
    ///
    /// Response bodies are untrusted input; the cap bounds memory use
    /// against hostile or misconfigured servers. Streaming responses are
    /// consumed incrementally and are not subject to it.
    pub fn max_response_size(mut self, max_response_size: usize) -> Self {
        self.max_response_size = Some(max_response_size);
        self
    }

    /// Adds one default header sent with every request. There are no
    /// default entries.
    ///
    /// A per-request header with the same name replaces the default value
    /// entirely (never both on the wire), and credentials are applied last
    /// so nothing can clobber them. An invalid name or value is reported
    /// as a configuration error by [`build`](Self::build).
    pub fn default_header(mut self, name: impl Into<String>, value: impl Into<String>) -> Self {
        let name = name.into();
        let value = value.into();
        match (http::header::HeaderName::from_bytes(name.as_bytes()), http::HeaderValue::from_str(&value)) {
            (Ok(parsed_name), Ok(parsed_value)) => {
                self.default_headers.append(parsed_name, parsed_value);
            }
            // Reported by `build()`; only the name is echoed, never the value.
            _ => self.invalid_header = Some(name),
        }
        self
    }

    /// Replaces the default headers sent with every request.
    ///
    /// Overwrites any headers added with [`default_header`](Self::default_header),
    /// including any invalid entry it recorded.
    pub fn default_headers(mut self, default_headers: http::HeaderMap) -> Self {
        self.default_headers = default_headers;
        // The invalid-header record described an entry in the map just
        // replaced; that entry no longer exists, so `build()` must not
        // fail on it after a wholesale replacement.
        self.invalid_header = None;
        self
    }

    /// Supplies a preconfigured `reqwest::Client` (proxies, custom TLS, etc.).
    #[cfg(feature = "reqwest")]
    #[deprecated(note = "use transport(ReqwestTransport::from_client(client)) instead")]
    pub fn http_client(mut self, http_client: reqwest::Client) -> Self {
        self.transport = Some(Arc::new(crate::transport::ReqwestTransport::from_client(http_client)));
        self
    }

    /// JWT Bearer token authentication
    pub fn bearer_token(mut self, value: impl Into<String>) -> Self {
        self.bearer_token = Some(value.into());
        self
    }

    /// Basic HTTP authentication
    pub fn username(mut self, value: impl Into<String>) -> Self {
        self.username = Some(value.into());
        self
    }

    /// Basic HTTP authentication
    pub fn password(mut self, value: impl Into<String>) -> Self {
        self.password = Some(value.into());
        self
    }

    /// API key request header
    pub fn api_key_header(mut self, value: impl Into<String>) -> Self {
        self.api_key_header = Some(value.into());
        self
    }

    /// API key query parameter
    pub fn api_key_query(mut self, value: impl Into<String>) -> Self {
        self.api_key_query = Some(value.into());
        self
    }

    /// API key browser cookie
    pub fn api_key_cookie(mut self, value: impl Into<String>) -> Self {
        self.api_key_cookie = Some(value.into());
        self
    }

    /// OAuth 2.0 authentication
    pub fn access_token(mut self, value: impl Into<String>) -> Self {
        self.access_token = Some(value.into());
        self
    }

    /// Sets the OAuth client id used for the client-credentials token exchange.
    pub fn client_id(mut self, value: impl Into<String>) -> Self {
        self.client_id = Some(value.into());
        self
    }

    /// Sets the OAuth client secret used for the client-credentials token exchange.
    pub fn client_secret(mut self, value: impl Into<String>) -> Self {
        self.client_secret = Some(value.into());
        self
    }

    /// Overrides the scopes requested by the client-credentials exchange.
    ///
    /// Defaults to the scopes the API description documents for this flow: `read:account write:planets read:planets`.
    /// A client granted only a subset must narrow the request here —
    /// asking for a scope it was not granted is rejected as
    /// `invalid_scope`, failing the very first API call.
    ///
    /// An empty iterator sends no `scope` parameter at all.
    pub fn oauth_scopes(mut self, scopes: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.oauth_scopes = Some(
            scopes
                .into_iter()
                .map(Into::into)
                .collect::<Vec<String>>()
                .join(" "),
        );
        self
    }

    /// Builds the client, resolving the base URL, transport, and timer.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Config`] when the base URL or a default header is
    /// invalid, when no transport is configured and the `reqwest` feature
    /// is disabled, or when no timer is available for retries/deadlines;
    /// [`Error::Transport`] when the bundled transport fails to construct.
    pub fn build(self) -> Result<Galaxy, Error> {
        if let Some(name) = self.invalid_header {
            return Err(Error::Config(format!("invalid default header {name:?}")));
        }
        let base_url = self
            .base_url
            .unwrap_or_else(|| self.environment.unwrap_or_default().base_url().to_string());
        let base_url = normalize_base_url(&base_url)?;
        // Validated once here; dispatch sends it as a plain header so the
        // user agent applies identically to every transport.
        let user_agent = http::HeaderValue::from_str(USER_AGENT).map_err(|error| Error::Config(error.to_string()))?;
        let max_retries = self.max_retries.unwrap_or(DEFAULT_MAX_RETRIES);
        // Stored as the caller-set value only: dispatch applies the 60 s
        // default per request, gated on the body being buffered non-multipart.
        let deadline = self.timeout;
        let max_response_size = self.max_response_size.unwrap_or(crate::http::DEFAULT_MAX_RESPONSE_SIZE);
        // Unset, the exchange asks for every scope the API description
        // documents. A client granted a subset narrows it through
        // `oauth_scopes`, since an over-broad request is refused wholesale
        // (`invalid_scope`) rather than downgraded.
        let oauth_scopes = self
            .oauth_scopes
            .unwrap_or_else(|| "read:account write:planets read:planets".to_string());
        // The token provider only exists once both halves of the
        // client-credentials pair are configured; with either missing there
        // is nothing to exchange, and the static token option (or no auth at
        // all) governs instead.
        let oauth = match (self.client_id, self.client_secret) {
            (Some(client_id), Some(client_secret)) => Some(crate::oauth::TokenProvider::new(
                &base_url,
                "https://galaxy.scalar.com/oauth/token",
                client_id,
                client_secret,
                &oauth_scopes,
            )),
            _ => None,
        };
        #[cfg(feature = "reqwest")]
        let transport: Arc<dyn Transport> = match self.transport {
            Some(transport) => transport,
            None => Arc::new(crate::transport::ReqwestTransport::new()?),
        };
        #[cfg(not(feature = "reqwest"))]
        let transport: Arc<dyn Transport> = self.transport.ok_or_else(|| {
            Error::Config(
                "no transport configured; enable the `reqwest` feature or supply one with `ClientBuilder::transport`"
                    .to_string(),
            )
        })?;
        #[cfg(feature = "tokio")]
        let sleep: Arc<dyn Sleep> = self
            .sleep
            .unwrap_or_else(|| Arc::new(crate::transport::TokioSleep));
        // Retries and request deadlines need a real timer, so a tokio-less
        // build without a caller-supplied sleeper fails loudly here instead
        // of silently dropping backoff/timeout behavior.
        #[cfg(not(feature = "tokio"))]
        let sleep: Arc<dyn Sleep> = self.sleep.ok_or_else(|| {
            Error::Config(
                "no sleeper configured; retries and timeouts need a timer — supply one with `ClientBuilder::sleeper` or enable the `tokio` feature"
                    .to_string(),
            )
        })?;
        Ok(Galaxy {
            inner: Arc::new(Inner {
                transport,
                sleep,
                base_url,
                auth: Auth {
                        bearer_token: self.bearer_token,
                        username: self.username,
                        password: self.password,
                        api_key_header: self.api_key_header,
                        api_key_query: self.api_key_query,
                        api_key_cookie: self.api_key_cookie,
                        access_token: self.access_token,
                },
                max_retries,
                deadline,
                max_response_size,
                default_headers: self.default_headers,
                user_agent,
                oauth,
            }),
        })
    }
}

impl std::fmt::Debug for GalaxyBuilder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GalaxyBuilder")
            .field("base_url", &self.base_url)
            .field("environment", &self.environment)
            .field("timeout", &self.timeout)
            .field("max_retries", &self.max_retries)
            .finish_non_exhaustive()
    }
}

/// Parses a base URL, ensuring a trailing slash so relative paths join correctly.
fn normalize_base_url(base_url: &str) -> Result<url::Url, Error> {
    let with_slash = if base_url.ends_with('/') {
        base_url.to_string()
    } else {
        format!("{base_url}/")
    };
    url::Url::parse(&with_slash).map_err(|error| Error::Config(error.to_string()))
}

/// Rejects a request URL whose origin differs from the client's base URL.
///
/// The only absolute URL that reaches `dispatch` is a next-page link the
/// *server* supplied (see `resolve_link`), and credentials are applied to
/// whatever URL comes out of the join. A link naming another origin would
/// therefore hand this client's token or API key to that origin, so it is
/// refused before the request is assembled and before anything is sent.
/// Dropping the credentials and following the link anyway is not a safer
/// fallback: a cross-origin next-page link is either a misconfigured base
/// URL or an attack, and an unauthenticated fetch would only surface as a
/// confusing 401. Scheme, host and port must all match (that is exactly what
/// comparing origins does). The error names only the two origins — the link
/// itself can carry a credential in its query string.
fn ensure_same_origin(base_url: &url::Url, url: &url::Url) -> Result<(), Error> {
    if url.origin() == base_url.origin() {
        return Ok(());
    }
    Err(Error::Config(format!(
        "refusing to send a request to {} because this client is configured for {}",
        url.origin().ascii_serialization(),
        base_url.origin().ascii_serialization()
    )))
}

/// Parses a header name, mapping an invalid (spec- or caller-derived) name
/// to a configuration error.
fn header_name(name: &str) -> Result<http::header::HeaderName, Error> {
    http::header::HeaderName::from_bytes(name.as_bytes())
        .map_err(|_| Error::Config(format!("invalid header name {name:?}")))
}

/// Parses a header value; the error names the header but never echoes the
/// value itself, which may be sensitive (idempotency keys, caller headers).
fn header_value(name: &str, value: &str) -> Result<http::HeaderValue, Error> {
    http::HeaderValue::from_str(value).map_err(|_| Error::Config(format!("invalid value for header {name:?}")))
}

/// Builds a header value from a credential, marking it sensitive so a
/// `Debug` of the request never prints it. The credential itself is
/// deliberately never echoed in the error.
fn auth_value(value: &str) -> Result<http::HeaderValue, Error> {
    let mut header = http::HeaderValue::from_str(value)
        .map_err(|_| Error::Config("credential contains characters not allowed in an HTTP header".to_string()))?;
    header.set_sensitive(true);
    Ok(header)
}

/// Encodes bytes as standard (padded) base64.
///
/// Used only to build a `Basic` Authorization header, so it is vendored
/// here rather than pulling in a base64 dependency.
fn base64_encode(input: &[u8]) -> String {
    const TABLE: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity(input.len().div_ceil(3) * 4);
    for chunk in input.chunks(3) {
        let b0 = u32::from(chunk[0]);
        let b1 = u32::from(*chunk.get(1).unwrap_or(&0));
        let b2 = u32::from(*chunk.get(2).unwrap_or(&0));
        let triple = (b0 << 16) | (b1 << 8) | b2;
        out.push(TABLE[((triple >> 18) & 0x3F) as usize] as char);
        out.push(TABLE[((triple >> 12) & 0x3F) as usize] as char);
        out.push(if chunk.len() > 1 { TABLE[((triple >> 6) & 0x3F) as usize] as char } else { '=' });
        out.push(if chunk.len() > 2 { TABLE[(triple & 0x3F) as usize] as char } else { '=' });
    }
    out
}

/// Reads an environment variable, treating an absent or blank value as unset.
fn read_env(name: &str) -> Option<String> {
    let value = std::env::var(name).ok()?;
    let trimmed = value.trim();
    if trimmed.is_empty() {
        None
    } else {
        Some(trimmed.to_string())
    }
}

