// Code generated by Scalar SDK Generator. DO NOT EDIT.
#![doc = include_str!("../README.md")]
#![recursion_limit = "512"]

pub mod client;
pub mod error;
#[doc(hidden)]
pub mod http;
pub mod models;
#[doc(hidden)]
pub mod oauth;
pub mod resources;
pub mod transport;
#[doc(hidden)]
pub mod transport_reqwest;
pub mod webhooks;

pub use client::Environment;
pub use client::Galaxy;
pub use client::GalaxyBuilder;
pub use error::{ApiError, Error};
pub use models::{
    AuthenticationCreateUserBody, CelestialBody, Credentials, PaginatedResource, PaginatedResourceMeta, Planet,
    PlanetAtmosphere, PlanetPhysicalProperties, PlanetPhysicalPropertiesTemperature, PlanetsDelteImageBody,
    PlanetsDelteImageResponse, Satellite, SatelliteOrbit, Token, User,
};
pub use webhooks::WebhookEvent;

/// The version of this crate, matching the published package version.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
