// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The Scalar Galaxy is an example OpenAPI document to test OpenAPI tools and libraries. It's a fictional universe with fictional planets and fictional data.
//!
//! ## Resources
//!
//! * https://github.com/scalar/scalar
//! * https://github.com/OAI/OpenAPI-Specification
//! * https://scalar.com
//!
//! ## Markdown Support
//!
//! All descriptions *can* contain ~~tons of text~~ **Markdown**. [If GitHub supports the syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax), chances are we're supporting it, too.
//!
//! <details>
//!   <summary>Examples</summary>
//!
//!   **Blockquotes**
//!
//!   > I love OpenAPI. <3
//!
//!   **Tables**
//!
//!   | Feature          | Availability |
//!   | ---------------- | ------------ |
//!   | Markdown Support | ✓            |
//!
//!   **Accordion**
//!
//!   ```text
//!   <details>
//!     <summary>Using Details Tags</summary>
//!     <p>HTML Example</p>
//!   </details>
//!   ```
//!
//!   **Images**
//!
//!   Yes, there's support for images, too!
//!
//!   ![Empty placeholder image showing the width/height](https://images.placeholders.dev/?width=1280&height=720)
//!
//!   **Alerts**
//!
//!   > [!tip]
//!   > You can use Markdown alerts in your descriptions.
//!
//! </details>
//!
//!
#![doc = include_str!("../README.md")]

pub mod error;
pub mod transport;
#[doc(hidden)]
pub mod transport_reqwest;
#[doc(hidden)]
pub mod http;
#[doc(hidden)]
pub mod oauth;
pub mod models;
pub mod client;
pub mod resources;
pub mod webhooks;

pub use models::{AuthenticationCreateUserBody, CelestialBody, Credentials, PaginatedResource, Planet, PlanetsUploadImageBody, PlanetsUploadImageResponse, Satellite, Token, User};
pub use client::Galaxy;
pub use client::GalaxyBuilder;
pub use client::Environment;
pub use webhooks::WebhookEvent;
pub use error::{ApiError, Error};

/// The version of this crate, matching the published package version.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
