// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models.

use serde::{Deserialize, Serialize};

/// A user
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

/// Credentials to authenticate a user
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Credentials {
    pub email: String,
    pub password: String,
}

/// A token to authenticate a user
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Token {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
}

/// A celestial body which can be either a planet or a satellite
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
#[non_exhaustive]
pub enum CelestialBody {
    #[serde(rename = "terrestrial")]
    Planet(Planet),
    #[serde(rename = "gas_giant")]
    Planet_(Planet),
    #[serde(rename = "ice_giant")]
    Planet__(Planet),
    #[serde(rename = "dwarf")]
    Planet___(Planet),
    #[serde(rename = "super_earth")]
    Planet____(Planet),
    #[serde(rename = "moon")]
    Satellite(Satellite),
    #[serde(rename = "asteroid")]
    Satellite_(Satellite),
    #[serde(rename = "comet")]
    Satellite__(Satellite),
    /// A variant not recognized by this version of the SDK, preserved verbatim.
    ///
    /// Match the specific variants first. Matching this one directly is an
    /// anti-pattern: that arm silently stops matching once a future SDK
    /// release adds the real variant.
    #[serde(untagged)]
    Unknown(serde_json::Value),
}

/// A planet in the Scalar Galaxy
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Planet {
    pub id: i64,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default, skip_serializing)]
    pub r#type: String,
    /// A score from 0 to 1 indicating potential habitability
    #[serde(rename = "habitabilityIndex", default, skip_serializing_if = "Option::is_none")]
    pub habitability_index: Option<f64>,
    #[serde(rename = "physicalProperties", default, skip_serializing_if = "Option::is_none")]
    pub physical_properties: Option<serde_json::Value>,
    /// Atmospheric composition
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub atmosphere: Option<Vec<serde_json::Value>>,
    #[serde(rename = "discoveredAt", default, skip_serializing_if = "Option::is_none")]
    pub discovered_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub satellites: Option<Vec<Satellite>>,
    /// A user
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creator: Option<User>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "lastUpdated", default, skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// URL which gets invoked upon a successful operation
    #[serde(rename = "successCallbackUrl", default, skip_serializing_if = "Option::is_none")]
    pub success_callback_url: Option<String>,
    /// URL which gets invoked upon a failed operation
    #[serde(rename = "failureCallbackUrl", default, skip_serializing_if = "Option::is_none")]
    pub failure_callback_url: Option<String>,
}

impl Planet {
    /// Creates a new `Planet` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `Planet { description: Some(…), ..Planet::new(id, name) }`.
    pub fn new(id: i64, name: impl Into<String>) -> Self {
        Self {
            id,
            name: name.into(),
            description: None,
            r#type: String::new(),
            habitability_index: None,
            physical_properties: None,
            atmosphere: None,
            discovered_at: None,
            image: None,
            satellites: None,
            creator: None,
            tags: None,
            last_updated: None,
            success_callback_url: None,
            failure_callback_url: None,
        }
    }
}

/// Every satellite in the Scalar Galaxy
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Satellite {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Diameter in kilometers
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub diameter: Option<f64>,
    #[serde(default, skip_serializing)]
    pub r#type: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub orbit: Option<serde_json::Value>,
}

impl Satellite {
    /// Creates a new `Satellite` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `Satellite { id: Some(…), ..Satellite::new(name) }`.
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            id: None,
            name: name.into(),
            description: None,
            diameter: None,
            r#type: String::new(),
            orbit: None,
        }
    }
}

/// A generic paginated resource. Specializing schemas bind the item type by declaring a `$dynamicAnchor` named `itemType`, the JSON Schema 2020-12 way to express `PaginatedResource<T>`.
///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct PaginatedResource {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub meta: Option<serde_json::Value>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct PlanetsUploadImageResponse {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The URL where the uploaded image can be accessed
    #[serde(rename = "imageUrl", default, skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// Timestamp when the image was uploaded
    #[serde(rename = "uploadedAt", default, skip_serializing_if = "Option::is_none")]
    pub uploaded_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Size of the uploaded image in bytes
    #[serde(rename = "fileSize", default, skip_serializing_if = "Option::is_none")]
    pub file_size: Option<i64>,
    /// The content type of the uploaded image
    #[serde(rename = "mimeType", default, skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PlanetsUploadImageBody {
    /// The image file to upload
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationCreateUserBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub email: String,
    pub password: String,
}

impl AuthenticationCreateUserBody {
    /// Creates a new `AuthenticationCreateUserBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `AuthenticationCreateUserBody { id: Some(…), ..AuthenticationCreateUserBody::new(email, password) }`.
    pub fn new(email: impl Into<String>, password: impl Into<String>) -> Self {
        Self {
            id: None,
            name: None,
            email: email.into(),
            password: password.into(),
        }
    }
}
