// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Pluggable HTTP transport: the one intentionally public runtime module.
//!
//! The generated client is transport-agnostic: every request is assembled as an
//! [`http::Request`]`<`[`SdkBody`]`>` and handed to a [`Transport`] — a single
//! dyn-compatible trait over the `http`/`http-body` 1.x vocabulary types. The
//! crate ships a default `reqwest`-backed transport behind the `reqwest` cargo
//! feature; bring your own backend (hyper, tower stacks, a corporate proxy
//! layer, WASM fetch) by implementing [`Transport`] and passing it to the
//! client builder — no conversion glue, because [`SdkBody`] implements
//! [`http_body::Body`] directly.
//!
//! Timer concerns (retry backoff, request deadlines) live in the separate
//! [`Sleep`] trait so a custom transport never has to reimplement timeout
//! logic: the runtime races `Sleep::sleep` against `Transport::execute`, which
//! means a BYO transport cannot silently drop deadlines.
//!
//! For tests, the `mock` cargo feature provides [`MockTransport`] (an ordered
//! in-process response queue with request capture) and [`InstantSleep`] so
//! retry tests run in microseconds without a network or a timer.

use std::fmt;
use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;
use std::task::{Context, Poll};
use std::time::Duration;

use bytes::{Bytes, BytesMut};
use futures_util::{Stream, StreamExt, stream};

/// A boxed, `Send` future — the return type of dyn-compatible async trait
/// methods ([`Transport::execute`], [`Sleep::sleep`]).
pub type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

/// A boxed, `Send` stream of body chunks: the internal payload representation
/// shared by [`SdkBody`] streaming variants and the multipart encoder.
type BytesStream = Pin<Box<dyn Stream<Item = Result<Bytes, TransportError>> + Send + 'static>>;

/// A boxed error source held by [`TransportError`].
type BoxError = Box<dyn std::error::Error + Send + Sync>;

/// The default `reqwest`-backed [`Transport`], re-exported here so transport
/// concerns live under one module (requires the `reqwest` cargo feature).
#[cfg(feature = "reqwest")]
pub use crate::transport_reqwest::ReqwestTransport;

/// An HTTP backend that executes one request and returns one response.
///
/// This is a deliberately "dumb" transport: retries, backoff, deadlines, auth,
/// and response decoding all live in the SDK runtime above it, so an
/// implementation only has to move one request to the wire and map the result
/// back. Implementations must be cheap to share (`Send + Sync`) because the
/// client stores the transport as `Arc<dyn Transport>`.
///
/// # Errors
///
/// `execute` resolves to a [`TransportError`] when the request could not be
/// completed at the transport level (connection, TLS, timeout, protocol). The
/// [`TransportErrorKind`] classification is **load-bearing for retry
/// semantics**: the retry layer replays [`TransportErrorKind::Connect`]
/// failures for any method (the request never reached the server) and
/// [`TransportErrorKind::Timeout`] failures only for idempotent requests. A
/// transport that lumps everything into [`TransportErrorKind::Other`] still
/// works, but loses connect-level retries.
///
/// # Examples
///
/// A bring-your-own backend is a struct plus one method:
///
/// ```no_run
/// use std::sync::Arc;
///
/// use scalar_galaxy::transport::{BoxFuture, SdkBody, Transport, TransportError, TransportErrorKind};
///
/// #[derive(Debug)]
/// struct MyTransport;
///
/// impl Transport for MyTransport {
///     fn execute(
///         &self,
///         request: http::Request<SdkBody>,
///     ) -> BoxFuture<'_, Result<http::Response<SdkBody>, TransportError>> {
///         Box::pin(async move {
///             // Hand `request` to your HTTP stack (hyper, tower, fetch, ...),
///             // then map its response into `http::Response<SdkBody>` and its
///             // failures into the matching `TransportErrorKind`.
///             let _ = request;
///             Err(TransportError::msg(TransportErrorKind::Other, "not wired up yet"))
///         })
///     }
/// }
///
/// let transport: Arc<dyn Transport> = Arc::new(MyTransport);
/// # let _ = transport;
/// ```
pub trait Transport: Send + Sync + fmt::Debug {
    /// Executes one HTTP request against the backend.
    ///
    /// # Errors
    ///
    /// Resolves to a [`TransportError`] classified by [`TransportErrorKind`]
    /// when the exchange fails below the HTTP status level; a non-success
    /// status is **not** a transport error and must be returned as a response.
    fn execute(
        &self,
        request: http::Request<SdkBody>,
    ) -> BoxFuture<'_, Result<http::Response<SdkBody>, TransportError>>;
}

// Shared transports are free: `Arc<dyn Transport>` (how the client stores its
// backend) and `Box<dyn Transport>` are themselves transports by delegation.
impl<T: Transport + ?Sized> Transport for Arc<T> {
    fn execute(
        &self,
        request: http::Request<SdkBody>,
    ) -> BoxFuture<'_, Result<http::Response<SdkBody>, TransportError>> {
        (**self).execute(request)
    }
}

impl<T: Transport + ?Sized> Transport for Box<T> {
    fn execute(
        &self,
        request: http::Request<SdkBody>,
    ) -> BoxFuture<'_, Result<http::Response<SdkBody>, TransportError>> {
        (**self).execute(request)
    }
}

/// An async timer used for retry backoff and request deadlines.
///
/// Kept separate from [`Transport`] (the smithy-rs `AsyncSleep` precedent) so
/// deadline enforcement is uniform: the runtime races `sleep(deadline)` against
/// [`Transport::execute`] regardless of which backend is plugged in. The
/// default implementation is [`TokioSleep`]; runtimes without tokio provide
/// their own via the client builder.
///
/// Do **not** implement this with a ready future to "disable" timers in
/// production code — a ready `sleep` turns retry backoff into a hot loop. The
/// only ready-future implementation this crate ships is the test-only
/// [`InstantSleep`] behind the `mock` feature.
pub trait Sleep: Send + Sync + fmt::Debug {
    /// Resolves after at least `duration` has elapsed.
    fn sleep(&self, duration: Duration) -> BoxFuture<'static, ()>;
}

impl<T: Sleep + ?Sized> Sleep for Arc<T> {
    fn sleep(&self, duration: Duration) -> BoxFuture<'static, ()> {
        (**self).sleep(duration)
    }
}

/// The default [`Sleep`] implementation, backed by `tokio::time`.
#[cfg(feature = "tokio")]
#[derive(Debug, Clone, Copy, Default)]
pub struct TokioSleep;

#[cfg(feature = "tokio")]
impl Sleep for TokioSleep {
    fn sleep(&self, duration: Duration) -> BoxFuture<'static, ()> {
        Box::pin(tokio::time::sleep(duration))
    }
}

/// The request/response body type used by every [`Transport`].
///
/// Internally a body is empty, fully buffered, a one-shot stream, or a
/// rebuildable stream. Buffered and rebuildable bodies can be replayed, so
/// requests carrying them are eligible for retries ([`SdkBody::is_retryable`]);
/// a one-shot stream is sent at most once and its request is single-attempt.
/// Streamed uploads opt back into retries via
/// [`SdkBody::from_retryable_stream`], which stores a closure that rebuilds a
/// fresh stream per attempt.
///
/// `SdkBody` implements [`http_body::Body`] (`Data = Bytes`), so hyper and
/// tower users can pass it to their stacks without conversion glue.
pub struct SdkBody {
    inner: Inner,
}

/// Internal representation of an [`SdkBody`].
enum Inner {
    /// No body.
    Empty,
    /// A fully buffered body; cloned cheaply for replay.
    Full(Bytes),
    /// A one-shot stream; consumed by the first attempt, never replayed.
    Stream(BytesStream),
    /// A rebuildable stream: `current` feeds the in-flight attempt and
    /// `rebuild` mints a fresh stream for each replay, so retrying never
    /// resumes a half-consumed stream.
    Retryable {
        /// Closure that produces a brand-new stream of the same payload.
        rebuild: Arc<dyn Fn() -> BytesStream + Send + Sync>,
        /// The stream being consumed by the current attempt.
        current: BytesStream,
    },
}

impl SdkBody {
    /// Creates an empty body.
    pub fn empty() -> Self {
        Self { inner: Inner::Empty }
    }

    /// Creates a fully buffered body; buffered bodies replay across retries.
    pub fn from_bytes(bytes: impl Into<Bytes>) -> Self {
        Self {
            inner: Inner::Full(bytes.into()),
        }
    }

    /// Creates a one-shot streaming body.
    ///
    /// The stream cannot be replayed, so a request carrying it is sent at most
    /// once and never retried; use [`SdkBody::from_retryable_stream`] when a
    /// streamed upload should stay retry-eligible.
    pub fn from_stream(body: impl Stream<Item = Result<Bytes, TransportError>> + Send + 'static) -> Self {
        Self {
            inner: Inner::Stream(Box::pin(body)),
        }
    }

    /// Creates a streaming body that stays retry-eligible.
    ///
    /// `rebuild` is invoked once per attempt to mint a fresh stream (e.g.
    /// re-open a file, re-slice a buffer), so a retry never resumes a
    /// half-consumed stream.
    pub fn from_retryable_stream<F, S>(rebuild: F) -> Self
    where
        F: Fn() -> S + Send + Sync + 'static,
        S: Stream<Item = Result<Bytes, TransportError>> + Send + 'static,
    {
        let rebuild: Arc<dyn Fn() -> BytesStream + Send + Sync> = Arc::new(move || Box::pin(rebuild()) as BytesStream);
        let current = rebuild();
        Self {
            inner: Inner::Retryable { rebuild, current },
        }
    }

    /// Buffers the entire body into one [`Bytes`] value.
    ///
    /// # Errors
    ///
    /// Returns the first [`TransportError`] produced by a streaming body; the
    /// buffered variants cannot fail.
    pub async fn collect(self) -> Result<Bytes, TransportError> {
        let mut body = match self.inner {
            Inner::Empty => return Ok(Bytes::new()),
            Inner::Full(bytes) => return Ok(bytes),
            Inner::Stream(body) | Inner::Retryable { current: body, .. } => body,
        };
        let mut buffer = BytesMut::new();
        while let Some(chunk) = body.next().await {
            buffer.extend_from_slice(&chunk?);
        }
        Ok(buffer.freeze())
    }

    /// Converts the body into a stream of data chunks.
    ///
    /// Buffered bodies yield at most one chunk; streaming bodies yield their
    /// chunks as they arrive. Errors surface as stream items so callers can
    /// distinguish a failed read from a clean end of stream.
    pub fn into_data_stream(self) -> impl Stream<Item = Result<Bytes, TransportError>> + Send + 'static {
        match self.inner {
            Inner::Empty => Box::pin(stream::empty()) as BytesStream,
            Inner::Full(bytes) => {
                if bytes.is_empty() {
                    Box::pin(stream::empty()) as BytesStream
                } else {
                    Box::pin(stream::once(std::future::ready(Ok(bytes)))) as BytesStream
                }
            }
            Inner::Stream(body) | Inner::Retryable { current: body, .. } => body,
        }
    }

    /// Whether the body can be replayed, making its request retry-eligible.
    ///
    /// `true` for empty, buffered, and rebuildable-stream bodies; `false` for
    /// one-shot streams, whose requests are sent exactly once.
    pub fn is_retryable(&self) -> bool {
        !matches!(self.inner, Inner::Stream(_))
    }

    /// Borrows the buffered payload, or `None` for streaming bodies.
    ///
    /// Lets a transport hand over a sized body (so it can send a
    /// `Content-Length`) without consuming or copying the request; an
    /// [`SdkBody::empty`] body borrows as zero bytes.
    pub fn as_bytes(&self) -> Option<&Bytes> {
        // A shared static empty payload so the empty body borrows like a
        // buffered one (`Bytes::new` is const and allocation-free).
        static EMPTY: Bytes = Bytes::new();
        match &self.inner {
            Inner::Empty => Some(&EMPTY),
            Inner::Full(bytes) => Some(bytes),
            Inner::Stream(_) | Inner::Retryable { .. } => None,
        }
    }

    /// Produces a fresh copy of the body for a retry attempt.
    ///
    /// Returns `Some` for empty and buffered bodies (a cheap clone) and for
    /// rebuildable streams (the rebuild closure mints a brand-new stream);
    /// returns `None` for one-shot streams, which the retry layer treats as
    /// single-attempt.
    pub fn try_replay(&self) -> Option<SdkBody> {
        match &self.inner {
            Inner::Empty => Some(Self::empty()),
            Inner::Full(bytes) => Some(Self::from_bytes(bytes.clone())),
            Inner::Stream(_) => None,
            Inner::Retryable { rebuild, .. } => Some(Self {
                inner: Inner::Retryable {
                    rebuild: Arc::clone(rebuild),
                    current: rebuild(),
                },
            }),
        }
    }
}

impl Default for SdkBody {
    fn default() -> Self {
        Self::empty()
    }
}

impl From<Bytes> for SdkBody {
    fn from(bytes: Bytes) -> Self {
        Self::from_bytes(bytes)
    }
}

impl From<Vec<u8>> for SdkBody {
    fn from(bytes: Vec<u8>) -> Self {
        Self::from_bytes(bytes)
    }
}

impl From<String> for SdkBody {
    fn from(text: String) -> Self {
        Self::from_bytes(text)
    }
}

// The zero-glue promise: `SdkBody` is a first-class `http-body` 1.x body, so a
// hyper/tower transport consumes it directly instead of converting it.
impl http_body::Body for SdkBody {
    type Data = Bytes;
    type Error = TransportError;

    fn poll_frame(
        self: Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Option<Result<http_body::Frame<Bytes>, TransportError>>> {
        // `SdkBody` is `Unpin` (streams are already boxed and pinned), so
        // projecting through `get_mut` is safe and keeps this impl free of
        // unsafe pin projection.
        let this = self.get_mut();
        match &mut this.inner {
            Inner::Empty => Poll::Ready(None),
            Inner::Full(bytes) => {
                let data = std::mem::take(bytes);
                this.inner = Inner::Empty;
                if data.is_empty() {
                    Poll::Ready(None)
                } else {
                    Poll::Ready(Some(Ok(http_body::Frame::data(data))))
                }
            }
            Inner::Stream(body) | Inner::Retryable { current: body, .. } => body
                .as_mut()
                .poll_next(cx)
                .map(|chunk| chunk.map(|result| result.map(http_body::Frame::data))),
        }
    }

    fn is_end_stream(&self) -> bool {
        match &self.inner {
            Inner::Empty => true,
            Inner::Full(bytes) => bytes.is_empty(),
            Inner::Stream(_) | Inner::Retryable { .. } => false,
        }
    }

    fn size_hint(&self) -> http_body::SizeHint {
        match &self.inner {
            Inner::Empty => http_body::SizeHint::with_exact(0),
            Inner::Full(bytes) => http_body::SizeHint::with_exact(bytes.len() as u64),
            Inner::Stream(_) | Inner::Retryable { .. } => http_body::SizeHint::default(),
        }
    }
}

impl fmt::Debug for SdkBody {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Streams are opaque; report the variant (and buffered length) so debug
        // logs stay useful without pretending to render a stream.
        match &self.inner {
            Inner::Empty => f.write_str("SdkBody::Empty"),
            Inner::Full(bytes) => write!(f, "SdkBody::Full({} bytes)", bytes.len()),
            Inner::Stream(_) => f.write_str("SdkBody::Stream"),
            Inner::Retryable { .. } => f.write_str("SdkBody::Retryable"),
        }
    }
}

/// A transport-level failure: the request could not be completed below the
/// HTTP status level.
///
/// The [`TransportErrorKind`] classification is **load-bearing for retry
/// semantics** — see [`TransportError::kind`]. The underlying cause, when one
/// exists, is exposed through [`std::error::Error::source`] and deliberately
/// **not** repeated in the `Display` output, so error-report chains print each
/// layer exactly once.
#[derive(Debug)]
pub struct TransportError {
    /// Classification consulted by the retry layer.
    kind: TransportErrorKind,
    /// Optional human-readable context, shown in `Display`.
    message: Option<String>,
    /// Optional underlying cause, exposed via `source()` only.
    source: Option<BoxError>,
}

/// Classification of a [`TransportError`], consulted by the retry layer.
///
/// Retry semantics per kind: `Connect` failures never reached the server and
/// are replayed for any method; `Timeout` failures may have been processed and
/// are replayed only for idempotent requests; `Body`, `Protocol`, and `Other`
/// are not retried. Custom transports should classify as precisely as they
/// can — mapping everything to `Other` forfeits connect-level retries.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum TransportErrorKind {
    /// The connection could not be established (DNS, TCP, TLS).
    Connect,
    /// The exchange exceeded a deadline before response headers arrived.
    Timeout,
    /// A request or response body failed while being read or written.
    Body,
    /// The peer violated the HTTP protocol (malformed response, bad frame).
    Protocol,
    /// Any other transport failure.
    Other,
}

impl TransportErrorKind {
    /// Human-readable label used by the `Display` implementation.
    fn label(self) -> &'static str {
        match self {
            Self::Connect => "connection failed",
            Self::Timeout => "request timed out",
            Self::Body => "body read/write failed",
            Self::Protocol => "protocol error",
            Self::Other => "transport error",
        }
    }
}

impl TransportError {
    /// Creates an error of `kind` wrapping an underlying cause.
    pub fn new(kind: TransportErrorKind, source: impl Into<BoxError>) -> Self {
        Self {
            kind,
            message: None,
            source: Some(source.into()),
        }
    }

    /// Creates an error of `kind` from a plain message, with no source.
    pub fn msg(kind: TransportErrorKind, message: impl Into<String>) -> Self {
        Self {
            kind,
            message: Some(message.into()),
            source: None,
        }
    }

    /// The retry-relevant classification of this error.
    pub fn kind(&self) -> TransportErrorKind {
        self.kind
    }

    /// Whether this is a [`TransportErrorKind::Connect`] failure (the request
    /// never reached the server, so it is safe to retry for any method).
    pub fn is_connect(&self) -> bool {
        self.kind == TransportErrorKind::Connect
    }

    /// Whether this is a [`TransportErrorKind::Timeout`] failure (the server
    /// may have processed the request, so only idempotent requests retry).
    pub fn is_timeout(&self) -> bool {
        self.kind == TransportErrorKind::Timeout
    }
}

impl fmt::Display for TransportError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // The source is intentionally not rendered here: it is reachable via
        // `Error::source()`, and rendering it in both places makes error-report
        // crates (anyhow, eyre, ...) print every cause twice.
        f.write_str(self.kind.label())?;
        if let Some(message) = &self.message {
            write!(f, ": {message}")?;
        }
        Ok(())
    }
}

impl std::error::Error for TransportError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.source
            .as_deref()
            .map(|source| source as &(dyn std::error::Error + 'static))
    }
}

/// Backend-agnostic `multipart/form-data` encoder (RFC 2046 / RFC 7578).
///
/// Emitted only for SDKs with multipart operations, behind the default-on
/// `multipart` cargo feature (which also carries the `getrandom` dependency
/// used for boundary entropy) — so crates without uploads ship neither.
/// Vendored so multipart uploads work identically on every [`Transport`]
/// instead of depending on a reqwest-only feature. All-buffered forms encode
/// to a buffered [`SdkBody`] and therefore stay retry-eligible; a form with
/// any streamed part encodes to a one-shot stream.
#[cfg(feature = "multipart")]
pub mod multipart {
    use super::{Bytes, BytesStream, SdkBody, Stream, StreamExt, TransportError, fmt, stream};

    /// One part of a `multipart/form-data` request body.
    pub struct Part {
        /// The form field name.
        name: String,
        /// Optional filename rendered into `Content-Disposition`.
        filename: Option<String>,
        /// Optional `Content-Type` header for the part.
        content_type: Option<String>,
        /// The part payload.
        body: PartBody,
    }

    /// Payload of a [`Part`]: buffered or streamed.
    enum PartBody {
        /// A fully buffered payload.
        Full(Bytes),
        /// A streamed payload; forces the whole form onto the streaming path.
        Stream(BytesStream),
    }

    impl Part {
        /// Creates a buffered part for `name`.
        pub fn bytes(name: impl Into<String>, body: impl Into<Bytes>) -> Self {
            Self {
                name: name.into(),
                filename: None,
                content_type: None,
                body: PartBody::Full(body.into()),
            }
        }

        /// Creates a streamed part for `name`.
        ///
        /// A streamed part makes the encoded form a one-shot stream, so the
        /// request carrying it is sent at most once (see
        /// [`SdkBody::is_retryable`]).
        pub fn stream(
            name: impl Into<String>,
            body: impl Stream<Item = Result<Bytes, TransportError>> + Send + 'static,
        ) -> Self {
            Self {
                name: name.into(),
                filename: None,
                content_type: None,
                body: PartBody::Stream(Box::pin(body)),
            }
        }

        /// Sets the filename rendered into the part's `Content-Disposition`.
        pub fn filename(mut self, filename: impl Into<String>) -> Self {
            self.filename = Some(filename.into());
            self
        }

        /// Sets the part's `Content-Type` header.
        pub fn content_type(mut self, content_type: impl Into<String>) -> Self {
            self.content_type = Some(content_type.into());
            self
        }
    }

    impl fmt::Debug for Part {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            let body = match &self.body {
                PartBody::Full(bytes) => format!("Full({} bytes)", bytes.len()),
                PartBody::Stream(_) => String::from("Stream"),
            };
            f.debug_struct("Part")
                .field("name", &self.name)
                .field("filename", &self.filename)
                .field("content_type", &self.content_type)
                .field("body", &body)
                .finish()
        }
    }

    /// A file or binary payload for a `multipart/form-data` request.
    ///
    /// Generated upload parameters take this type instead of a `String`, so a
    /// caller passes real bytes (or a stream) plus the `filename=` and
    /// `Content-Type` metadata servers use to interpret the upload. It is the
    /// field-name-free half of a [`Part`]: the generated operation supplies the
    /// wire field name, the caller supplies the payload.
    ///
    /// # Examples
    ///
    /// ```
    /// use scalar_galaxy::transport::multipart::Upload;
    ///
    /// let upload = Upload::from_bytes("hello world")
    ///     .filename("greeting.txt")
    ///     .content_type("text/plain");
    /// // Generated upload parameters take the `Upload` itself; the operation
    /// // attaches the wire field name when it builds the form.
    /// let part = upload.into_part("attachment", None);
    /// ```
    pub struct Upload {
        /// The payload, buffered or streamed.
        body: PartBody,
        /// Optional filename rendered into `Content-Disposition`.
        filename: Option<String>,
        /// Optional `Content-Type` override for the part.
        content_type: Option<String>,
    }

    impl Upload {
        /// Creates an upload from fully buffered bytes.
        ///
        /// A form whose parts are all buffered encodes to a buffered body and
        /// therefore stays retry-eligible.
        pub fn from_bytes(bytes: impl Into<Bytes>) -> Self {
            Self {
                body: PartBody::Full(bytes.into()),
                filename: None,
                content_type: None,
            }
        }

        /// Creates an upload that streams its payload, for files too large to
        /// hold in memory.
        ///
        /// A streamed part makes the encoded form a one-shot stream, so the
        /// request carrying it is sent at most once (see
        /// [`SdkBody::is_retryable`]).
        pub fn from_stream(body: impl Stream<Item = Result<Bytes, TransportError>> + Send + 'static) -> Self {
            Self {
                body: PartBody::Stream(Box::pin(body)),
                filename: None,
                content_type: None,
            }
        }

        /// Sets the filename rendered into the part's `Content-Disposition`.
        ///
        /// Unset, [`into_part`](Upload::into_part) falls back to the form field
        /// name so the part is still parsed as a file rather than a text field.
        pub fn filename(mut self, filename: impl Into<String>) -> Self {
            self.filename = Some(filename.into());
            self
        }

        /// Overrides the part's `Content-Type`.
        ///
        /// Unset, the part uses the content type the API description declares
        /// for it (if any).
        pub fn content_type(mut self, content_type: impl Into<String>) -> Self {
            self.content_type = Some(content_type.into());
            self
        }

        /// Converts this upload into a named [`Part`], falling back to
        /// `default_content_type` when the caller set none.
        ///
        /// Generated operations call this with the field name and the content
        /// type the API description declares for that part, which is why the
        /// caller's own [`Upload::content_type`] has to win: the spec value is
        /// a default, not an override.
        ///
        /// An upload with no [`filename`](Upload::filename) still gets one: the
        /// field name. A `Content-Disposition` without `filename=` is a *text*
        /// field to every mainstream server-side parser (multer, busboy, Rack,
        /// Spring, FastAPI), so omitting it would silently turn a file upload
        /// into a form field. An explicit filename always wins.
        pub fn into_part(self, name: impl Into<String>, default_content_type: Option<&str>) -> Part {
            let name = name.into();
            Part {
                filename: Some(self.filename.unwrap_or_else(|| name.clone())),
                name,
                content_type: self
                    .content_type
                    .or_else(|| default_content_type.map(str::to_string)),
                body: self.body,
            }
        }
    }

    impl fmt::Debug for Upload {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            let body = match &self.body {
                PartBody::Full(bytes) => format!("Full({} bytes)", bytes.len()),
                PartBody::Stream(_) => String::from("Stream"),
            };
            f.debug_struct("Upload")
                .field("filename", &self.filename)
                .field("content_type", &self.content_type)
                .field("body", &body)
                .finish()
        }
    }

    /// Encodes `parts` into a `multipart/form-data` body.
    ///
    /// Returns the full `Content-Type` header value (including the generated
    /// boundary) and the encoded body. When every part is buffered the body is
    /// buffered too — and therefore retry-eligible; if any part streams, the
    /// whole body is a one-shot stream.
    ///
    /// The boundary carries 128 bits of OS randomness so untrusted part
    /// content cannot predict and embed it. Field names and filenames are
    /// escaped per RFC 7578 (double quote, CR, and LF percent-encoded) so
    /// spec- or user-derived values cannot inject headers or close the part.
    pub fn encode(parts: Vec<Part>) -> (String, SdkBody) {
        let boundary = boundary();
        let content_type = format!("multipart/form-data; boundary={boundary}");
        let streaming = parts.iter().any(|part| matches!(part.body, PartBody::Stream(_)));
        if streaming {
            (content_type, SdkBody::from_stream(encode_streaming(&boundary, parts)))
        } else {
            (content_type, SdkBody::from_bytes(encode_buffered(&boundary, parts)))
        }
    }

    /// Encodes an all-buffered form into a single byte buffer.
    fn encode_buffered(boundary: &str, parts: Vec<Part>) -> Bytes {
        let mut buffer = Vec::new();
        for part in parts {
            buffer.extend_from_slice(part_header(boundary, &part).as_bytes());
            if let PartBody::Full(bytes) = part.body {
                buffer.extend_from_slice(&bytes);
            }
            buffer.extend_from_slice(b"\r\n");
        }
        buffer.extend_from_slice(terminator(boundary).as_bytes());
        Bytes::from(buffer)
    }

    /// Encodes a form containing at least one streamed part as a chunk stream.
    ///
    /// Each part contributes a header chunk, its payload (buffered chunk or
    /// pass-through stream), and a CRLF chunk; segments are flattened in order
    /// so the wire layout matches the buffered encoding byte for byte.
    fn encode_streaming(
        boundary: &str,
        parts: Vec<Part>,
    ) -> impl Stream<Item = Result<Bytes, TransportError>> + Send + 'static {
        let mut segments: Vec<BytesStream> = Vec::new();
        for part in parts {
            let mut header = part_header(boundary, &part).into_bytes();
            match part.body {
                PartBody::Full(bytes) => {
                    // Fold the buffered payload into the header chunk so small
                    // parts do not fragment the stream.
                    header.extend_from_slice(&bytes);
                    header.extend_from_slice(b"\r\n");
                    segments.push(chunk(Bytes::from(header)));
                }
                PartBody::Stream(body) => {
                    segments.push(chunk(Bytes::from(header)));
                    segments.push(body);
                    segments.push(chunk(Bytes::from_static(b"\r\n")));
                }
            }
        }
        segments.push(chunk(Bytes::from(terminator(boundary))));
        stream::iter(segments).flatten()
    }

    /// Wraps one buffered chunk as a single-item stream segment.
    fn chunk(bytes: Bytes) -> BytesStream {
        Box::pin(stream::once(std::future::ready(Ok(bytes))))
    }

    /// Renders the part's opening boundary line and headers, through the blank
    /// line that precedes the payload.
    fn part_header(boundary: &str, part: &Part) -> String {
        let mut header = format!(
            "--{boundary}\r\nContent-Disposition: form-data; name=\"{}\"",
            escape_disposition(&part.name)
        );
        if let Some(filename) = &part.filename {
            header.push_str(&format!("; filename=\"{}\"", escape_disposition(filename)));
        }
        header.push_str("\r\n");
        if let Some(content_type) = &part.content_type {
            header.push_str(&format!("Content-Type: {}\r\n", sanitize_header_value(content_type)));
        }
        header.push_str("\r\n");
        header
    }

    /// Renders the closing boundary line.
    fn terminator(boundary: &str) -> String {
        format!("--{boundary}--\r\n")
    }

    /// Generates a boundary with 128 bits of OS randomness.
    ///
    /// This is the crate's one entropy exception: multipart boundaries must be
    /// unpredictable so untrusted part content cannot embed them. If the OS
    /// RNG fails (effectively unheard of), the infallible signature falls back
    /// to wall-clock nanos — boundary uniqueness degrades but encoding never
    /// panics.
    fn boundary() -> String {
        const HEX: &[u8; 16] = b"0123456789abcdef";
        let mut seed = [0u8; 16];
        if getrandom::fill(&mut seed).is_err() {
            let nanos = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|elapsed| elapsed.as_nanos())
                .unwrap_or(0);
            seed = nanos.to_le_bytes();
        }
        let mut boundary = String::with_capacity(7 + seed.len() * 2);
        boundary.push_str("scalar-");
        for byte in seed {
            boundary.push(HEX[(byte >> 4) as usize] as char);
            boundary.push(HEX[(byte & 0x0f) as usize] as char);
        }
        boundary
    }

    /// Percent-encodes the characters RFC 7578 §4.2 requires escaping in
    /// `Content-Disposition` name/filename values, so a quote or newline in a
    /// user-supplied filename cannot break out of the quoted string or inject
    /// a header line.
    fn escape_disposition(value: &str) -> String {
        let mut escaped = String::with_capacity(value.len());
        for character in value.chars() {
            match character {
                '"' => escaped.push_str("%22"),
                '\r' => escaped.push_str("%0D"),
                '\n' => escaped.push_str("%0A"),
                _ => escaped.push(character),
            }
        }
        escaped
    }

    /// Strips CR/LF from a header value so a user-supplied content type cannot
    /// inject additional part headers.
    fn sanitize_header_value(value: &str) -> String {
        value
            .chars()
            .filter(|character| !matches!(character, '\r' | '\n'))
            .collect()
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        /// Buffers an encoded form so assertions can read the wire bytes.
        fn encoded(parts: Vec<Part>) -> (String, String) {
            let (content_type, body) = encode(parts);
            let bytes = body.as_bytes().expect("an all-buffered form encodes to a buffered body");
            (content_type, String::from_utf8_lossy(bytes).into_owned())
        }

        #[test]
        fn upload_round_trips_filename_and_content_type_into_the_encoded_form() {
            let upload = Upload::from_bytes("PDF-BYTES")
                .filename("report.pdf")
                .content_type("application/pdf");

            let (content_type, body) = encoded(vec![upload.into_part("file", None)]);

            let boundary = content_type
                .strip_prefix("multipart/form-data; boundary=")
                .expect("the content type carries the generated boundary");
            assert!(body.contains(&format!("--{boundary}\r\n")), "opening boundary missing: {body}");
            assert!(
                body.contains("Content-Disposition: form-data; name=\"file\"; filename=\"report.pdf\"\r\n"),
                "disposition missing name/filename: {body}"
            );
            assert!(body.contains("Content-Type: application/pdf\r\n"), "part content type missing: {body}");
            // The payload rides verbatim: an upload is bytes, never a
            // JSON-stringified scalar.
            assert!(body.contains("\r\n\r\nPDF-BYTES\r\n"), "file bytes missing: {body}");
        }

        #[test]
        fn upload_content_type_wins_over_the_spec_declared_default() {
            // `into_part`'s default is what the API description declares for the
            // part; an explicit caller value must override it, not the reverse.
            let explicit = Upload::from_bytes("x").content_type("image/png");
            let (_, body) = encoded(vec![explicit.into_part("file", Some("application/pdf"))]);
            assert!(body.contains("Content-Type: image/png\r\n"), "caller content type lost: {body}");
            assert!(!body.contains("application/pdf"), "spec default overrode the caller: {body}");

            let bare = Upload::from_bytes("x");
            let (_, body) = encoded(vec![bare.into_part("file", Some("application/pdf"))]);
            assert!(body.contains("Content-Type: application/pdf\r\n"), "spec default missing: {body}");
        }

        #[test]
        fn an_upload_without_a_filename_still_encodes_as_a_file_part() {
            // No `filename=` in `Content-Disposition` makes multer/busboy/Rack/
            // Spring/FastAPI parse the part as a plain TEXT field, so the file
            // never reaches the server's file handler. The field name is the
            // default; an explicit filename still wins (asserted below).
            let (_, body) = encoded(vec![Upload::from_bytes("PDF-BYTES").into_part("file", None)]);
            assert!(
                body.contains("Content-Disposition: form-data; name=\"file\"; filename=\"file\"\r\n"),
                "an upload with no caller filename must still carry filename=: {body}"
            );

            let (_, body) = encoded(vec![
                Upload::from_bytes("PDF-BYTES")
                    .filename("report.pdf")
                    .into_part("file", None),
            ]);
            assert!(
                body.contains("Content-Disposition: form-data; name=\"file\"; filename=\"report.pdf\"\r\n"),
                "an explicit filename must win over the default: {body}"
            );

            // A non-file part built through `Part::bytes` is unaffected: it stays
            // a text field with no `filename=`.
            let (_, body) = encoded(vec![Part::bytes("caption", "hello")]);
            assert!(
                body.contains("Content-Disposition: form-data; name=\"caption\"\r\n"),
                "a scalar part must not gain a filename: {body}"
            );
        }

        #[test]
        fn a_streamed_upload_makes_the_whole_form_single_attempt() {
            let streamed = Upload::from_stream(stream::once(std::future::ready(Ok(Bytes::from_static(b"chunk")))));

            let (_, buffered) = encode(vec![Upload::from_bytes("x").into_part("file", None)]);
            let (_, streaming) = encode(vec![streamed.into_part("file", None)]);

            // A buffered form replays across retries; a streamed one cannot be
            // rewound, so the retry layer must send it exactly once.
            assert!(buffered.is_retryable(), "an all-buffered form must stay retry-eligible");
            assert!(!streaming.is_retryable(), "a streamed part must force a single attempt");
        }
    }
}

/// An in-process [`Transport`] for tests: an ordered response queue plus
/// request capture, with no network and no external dependencies.
///
/// `MockTransport` is `Clone` with shared interior state: clone one into the
/// client builder and keep the original to assert on
/// [`MockTransport::requests`] afterwards. Responses are returned strictly in
/// the order they were enqueued.
///
/// # Panics
///
/// Executing a request when the queue is empty **panics** with a clear
/// message. This is the crate's documented test-only carve-out: in a test, an
/// unexpected extra request is a bug worth failing loudly on.
///
/// # Examples
///
/// ```no_run
/// use scalar_galaxy::transport::{MockTransport, SdkBody, Transport};
///
/// # async fn demo() {
/// let mock = MockTransport::new();
/// mock.enqueue(200, r#"{"id":"user_1"}"#);
///
/// // Normally the clone goes into the client builder; the mock itself is a
/// // `Transport`, so it can also be driven directly.
/// let transport = mock.clone();
/// let request = http::Request::post("https://api.example.com/users")
///     .body(SdkBody::from_bytes(r#"{"name":"Ada"}"#))
///     .expect("valid request");
/// let response = transport.execute(request).await.expect("a queued response");
/// assert_eq!(response.status(), 200);
///
/// let recorded = mock.requests();
/// assert_eq!(recorded.len(), 1);
/// assert_eq!(recorded[0].method, http::Method::POST);
/// assert_eq!(&recorded[0].body[..], &br#"{"name":"Ada"}"#[..]);
/// # }
/// ```
#[cfg(feature = "mock")]
#[derive(Debug, Clone, Default)]
pub struct MockTransport {
    /// Shared interior so clones observe one queue and one request log.
    state: Arc<std::sync::Mutex<MockState>>,
}

/// Interior state shared by every clone of a [`MockTransport`].
#[cfg(feature = "mock")]
#[derive(Debug, Default)]
struct MockState {
    /// Responses handed out in FIFO order.
    queue: std::collections::VecDeque<http::Response<SdkBody>>,
    /// Every executed request, in arrival order.
    requests: Vec<RecordedRequest>,
}

/// A request captured by [`MockTransport`], with its body fully buffered so
/// tests can assert on the exact bytes sent.
#[cfg(feature = "mock")]
#[derive(Debug, Clone)]
pub struct RecordedRequest {
    /// The request method.
    pub method: http::Method,
    /// The full request URI.
    pub uri: http::Uri,
    /// The request headers.
    pub headers: http::HeaderMap,
    /// The collected request body.
    pub body: Bytes,
}

#[cfg(feature = "mock")]
impl MockTransport {
    /// Creates a mock transport with an empty response queue.
    pub fn new() -> Self {
        Self::default()
    }

    /// Enqueues a `status` response with `body` and a
    /// `content-type: application/json` header, returning `&self` for
    /// chaining.
    ///
    /// # Panics
    ///
    /// Panics when `status` is not a valid HTTP status code — a mock
    /// configured with an impossible response is a test bug (test-only
    /// carve-out).
    pub fn enqueue(&self, status: u16, body: impl Into<Bytes>) -> &Self {
        let response = http::Response::builder()
            .status(status)
            .header(http::header::CONTENT_TYPE, "application/json")
            .body(SdkBody::from_bytes(body.into()))
            .unwrap_or_else(|error| panic!("MockTransport::enqueue: invalid response (status {status}): {error}"));
        self.state().queue.push_back(response);
        self
    }

    /// Enqueues a pre-built response, for cases [`MockTransport::enqueue`]
    /// does not cover (custom headers, streaming bodies), returning `&self`
    /// for chaining.
    pub fn enqueue_response(&self, response: http::Response<SdkBody>) -> &Self {
        self.state().queue.push_back(response);
        self
    }

    /// All requests executed so far, in order, with bodies buffered.
    pub fn requests(&self) -> Vec<RecordedRequest> {
        self.state().requests.clone()
    }

    /// Locks the shared state, recovering from a poisoned lock so one failed
    /// test thread does not cascade panics into unrelated assertions.
    fn state(&self) -> std::sync::MutexGuard<'_, MockState> {
        self.state.lock().unwrap_or_else(std::sync::PoisonError::into_inner)
    }
}

#[cfg(feature = "mock")]
impl Transport for MockTransport {
    fn execute(
        &self,
        request: http::Request<SdkBody>,
    ) -> BoxFuture<'_, Result<http::Response<SdkBody>, TransportError>> {
        let state = Arc::clone(&self.state);
        Box::pin(async move {
            let (parts, body) = request.into_parts();
            // Collect before locking: buffering the body is async and must not
            // hold the mutex across an await point.
            let body = body.collect().await?;
            let mut state = state.lock().unwrap_or_else(std::sync::PoisonError::into_inner);
            state.requests.push(RecordedRequest {
                method: parts.method,
                uri: parts.uri,
                headers: parts.headers,
                body,
            });
            match state.queue.pop_front() {
                Some(response) => Ok(response),
                // Test-only carve-out: an unexpected extra request in a test
                // should fail loudly, not limp along with a synthetic error.
                None => panic!(
                    "MockTransport response queue is exhausted: enqueue a response for every request the test issues"
                ),
            }
        })
    }
}

/// A [`Sleep`] whose futures resolve immediately, so retry/backoff tests run
/// in microseconds.
///
/// Test-only by design: wired into production code it turns every backoff into
/// a hot loop. Pair it with [`MockTransport`] in the client builder.
#[cfg(feature = "mock")]
#[derive(Debug, Clone, Copy, Default)]
pub struct InstantSleep;

#[cfg(feature = "mock")]
impl Sleep for InstantSleep {
    fn sleep(&self, _duration: Duration) -> BoxFuture<'static, ()> {
        Box::pin(std::future::ready(()))
    }
}
