// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Inbound webhook event types and verification.

use crate::error::Error;

/// A decoded inbound webhook event.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum WebhookEvent {
    Unwrap(crate::models::Planet),
}

impl WebhookEvent {
    /// Parses a webhook payload, dispatching on the event-type string.
    ///
    /// `event_type` is the value the webhook delivers to identify the event
    /// (typically in a request header); `payload` is the raw JSON body.
    pub fn parse(event_type: &str, payload: &[u8]) -> Result<Self, Error> {
        match event_type {
            "newPlanet" => Ok(Self::Unwrap(serde_json::from_slice(payload)?)),
            other => Err(Error::Config(format!("unrecognized webhook event type: {other}"))),
        }
    }
}

/// Verifies an inbound webhook's `webhook-signature` HMAC-Sha256 signature.
///
/// Returns `Ok(())` when the hex-encoded signature matches the HMAC of the
/// raw request body under `secret`, using a constant-time comparison.
pub fn verify_signature(secret: &[u8], payload: &[u8], signature: &str) -> Result<(), Error> {
    use hmac::{Hmac, KeyInit, Mac};
    use sha2::Sha256;

    let mut mac = Hmac::<Sha256>::new_from_slice(secret).map_err(|error| Error::Config(error.to_string()))?;
    mac.update(payload);
    let expected = mac.finalize().into_bytes();
    let provided = decode_hex(signature)?;
    if provided.len() == expected.len() && constant_time_eq(&provided, &expected) {
        Ok(())
    } else {
        Err(Error::Config("webhook signature verification failed".to_string()))
    }
}

/// Decodes a lowercase/uppercase hex string into bytes.
fn decode_hex(value: &str) -> Result<Vec<u8>, Error> {
    // Providers prefix the hex digest with their algorithm name
    // (`sha256=…`, `sha512=…`, `sha1=…`); strip everything up to and
    // including the first `=` so any algorithm prefix is handled, while a
    // bare hex string (no prefix) passes through unchanged.
    let value = value.split_once('=').map_or(value, |(_, hex)| hex);
    if value.len() % 2 != 0 {
        return Err(Error::Config("invalid webhook signature encoding".to_string()));
    }
    (0..value.len())
        .step_by(2)
        .map(|index| u8::from_str_radix(&value[index..index + 2], 16).map_err(|error| Error::Config(error.to_string())))
        .collect()
}

/// Compares two byte slices in constant time to avoid timing leaks.
fn constant_time_eq(left: &[u8], right: &[u8]) -> bool {
    let mut diff = 0u8;
    for (a, b) in left.iter().zip(right.iter()) {
        diff |= a ^ b;
    }
    diff == 0
}
